/* eslint-disable */
/** Auto-generated by scripts/generate-place-readings.mjs — do not edit by hand. */
import type { NormanReadingEntry } from './types';

export const PLACE_READING_ENTRIES: NormanReadingEntry[] = [
  {
    "slug": "node-caen",
    "title": "Caen",
    "description": "Ducal seat, abbey center. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-caen",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-falaise",
    "title": "Falaise Castle",
    "description": "Birthplace of William the Conqueror. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-falaise",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-bayeux",
    "title": "Bayeux",
    "description": "Cathedral city, tapestry site. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-bayeux",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-mont-saint-michel",
    "title": "Mont-Saint-Michel",
    "description": "Fortified abbey on the frontier. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-mont-saint-michel",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-avranches",
    "title": "Avranches",
    "description": "Border stronghold, episcopal see. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-avranches",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-london",
    "title": "London (Tower)",
    "description": "Capital of Norman England. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-london",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-hastings",
    "title": "Hastings",
    "description": "Battle site, 1066. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-hastings",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-windsor",
    "title": "Windsor Castle",
    "description": "Royal residence. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-windsor",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-dover",
    "title": "Dover Castle",
    "description": "Strategic coastal fortress. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-dover",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-york",
    "title": "York",
    "description": "Northern administrative center. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-york",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-durham",
    "title": "Durham Castle",
    "description": "Prince-Bishops stronghold. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-durham",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-norwich",
    "title": "Norwich Castle",
    "description": "East Anglian administrative seat. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-norwich",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-warwick",
    "title": "Warwick Castle",
    "description": "Midlands stronghold. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-warwick",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-lincoln",
    "title": "Lincoln Castle",
    "description": "Strategic hilltop fortress. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-lincoln",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-chepstow",
    "title": "Chepstow Castle",
    "description": "First Norman stone castle in Wales. Long-form companion to the Norman Expansion pin (Wales).",
    "linkedNodeId": "node-chepstow",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Wales"
    ]
  },
  {
    "slug": "node-cardiff",
    "title": "Cardiff Castle",
    "description": "Welsh Marcher stronghold. Long-form companion to the Norman Expansion pin (Wales).",
    "linkedNodeId": "node-cardiff",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Wales"
    ]
  },
  {
    "slug": "node-pembroke",
    "title": "Pembroke Castle",
    "description": "Gateway to Ireland. Long-form companion to the Norman Expansion pin (Wales).",
    "linkedNodeId": "node-pembroke",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Wales"
    ]
  },
  {
    "slug": "node-edinburgh",
    "title": "Edinburgh",
    "description": "Norman feudal influence in Scotland. Long-form companion to the Norman Expansion pin (Scotland).",
    "linkedNodeId": "node-edinburgh",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Scotland"
    ]
  },
  {
    "slug": "node-dublin",
    "title": "Dublin",
    "description": "Anglo-Norman foothold in Ireland. Long-form companion to the Norman Expansion pin (Ireland).",
    "linkedNodeId": "node-dublin",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Ireland"
    ]
  },
  {
    "slug": "node-trim",
    "title": "Trim Castle",
    "description": "Largest Anglo-Norman castle in Ireland. Long-form companion to the Norman Expansion pin (Ireland).",
    "linkedNodeId": "node-trim",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Ireland"
    ]
  },
  {
    "slug": "node-wexford",
    "title": "Wexford",
    "description": "Early Anglo-Norman landing site. Long-form companion to the Norman Expansion pin (Ireland).",
    "linkedNodeId": "node-wexford",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Ireland"
    ]
  },
  {
    "slug": "node-waterford",
    "title": "Waterford",
    "description": "Strongbow capture, key port. Long-form companion to the Norman Expansion pin (Ireland).",
    "linkedNodeId": "node-waterford",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Ireland"
    ]
  },
  {
    "slug": "node-palermo",
    "title": "Palermo",
    "description": "Capital of Norman Sicily. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-palermo",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-melfi",
    "title": "Melfi",
    "description": "Early Norman capital in Italy. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-melfi",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-bari",
    "title": "Bari",
    "description": "Apulian port, Norman conquest. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-bari",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-salerno",
    "title": "Salerno",
    "description": "Principality, early Norman base. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-salerno",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-messina",
    "title": "Messina",
    "description": "Sicilian port, invasion staging. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-messina",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-naples",
    "title": "Naples",
    "description": "Southern Italian stronghold. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-naples",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-catania",
    "title": "Catania",
    "description": "Sicilian episcopal city. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-catania",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-reggio-calabria",
    "title": "Reggio Calabria",
    "description": "Toe of Italy, staging for Sicily. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-reggio-calabria",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-aversa",
    "title": "Aversa",
    "description": "First Norman county in Italy. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-aversa",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-cefalu",
    "title": "Cefalù",
    "description": "Norman cathedral city. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-cefalu",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-monreale",
    "title": "Monreale",
    "description": "Royal abbey and cathedral. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-monreale",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-antioch",
    "title": "Antioch",
    "description": "Norman-led Crusader principality. Long-form companion to the Norman Expansion pin (Crusader states).",
    "linkedNodeId": "node-antioch",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Crusader states"
    ]
  },
  {
    "slug": "node-tripoli",
    "title": "Tripoli",
    "description": "Crusader county with Norman ties. Long-form companion to the Norman Expansion pin (Crusader states).",
    "linkedNodeId": "node-tripoli",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Crusader states"
    ]
  },
  {
    "slug": "node-edessa",
    "title": "Edessa",
    "description": "First Crusader state. Long-form companion to the Norman Expansion pin (Crusader states).",
    "linkedNodeId": "node-edessa",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Crusader states"
    ]
  },
  {
    "slug": "node-tunis",
    "title": "Tunis",
    "description": "Norman Ifriqiya coastal holding. Long-form companion to the Norman Expansion pin (Ifriqiya).",
    "linkedNodeId": "node-tunis",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Ifriqiya"
    ]
  },
  {
    "slug": "node-dyrrachium",
    "title": "Dyrrachium",
    "description": "Battle site, Byzantine frontier. Long-form companion to the Norman Expansion pin (Expedition).",
    "linkedNodeId": "node-dyrrachium",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Expedition"
    ]
  },
  {
    "slug": "node-lisbon",
    "title": "Lisbon",
    "description": "Norman participation in siege. Long-form companion to the Norman Expansion pin (Expedition).",
    "linkedNodeId": "node-lisbon",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Expedition"
    ]
  },
  {
    "slug": "node-tarragona",
    "title": "Tarragona",
    "description": "Norman Reconquista involvement. Long-form companion to the Norman Expansion pin (Expedition).",
    "linkedNodeId": "node-tarragona",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Expedition"
    ]
  },
  {
    "slug": "node-limassol",
    "title": "Limassol",
    "description": "Richard I conquest of Cyprus. Long-form companion to the Norman Expansion pin (Expedition).",
    "linkedNodeId": "node-limassol",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Expedition"
    ]
  },
  {
    "slug": "node-mahdia",
    "title": "Mahdia",
    "description": "Norman conquest in Ifriqiya. Long-form companion to the Norman Expansion pin (Ifriqiya).",
    "linkedNodeId": "node-mahdia",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Ifriqiya"
    ]
  },
  {
    "slug": "node-colchester-castle",
    "title": "Colchester Castle",
    "description": "Largest Norman keep in England, built over a Roman temple. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-colchester-castle",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-rochester-castle",
    "title": "Rochester Castle",
    "description": "Tallest Norman keep in England at 113 feet. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-rochester-castle",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-arundel-castle",
    "title": "Arundel Castle",
    "description": "Major motte-and-bailey on a towering mound. Long-form companion to the Norman Expansion pin (England).",
    "linkedNodeId": "node-arundel-castle",
    "defaultEraId": "norman-expansion",
    "tags": [
      "England"
    ]
  },
  {
    "slug": "node-chateau-gaillard",
    "title": "Château Gaillard",
    "description": "Richard the Lionheart's fortress defending the Seine valley. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-chateau-gaillard",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-gisors",
    "title": "Gisors Castle",
    "description": "Major frontier fortress with motte-and-bailey core. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-gisors",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-pirou",
    "title": "Château de Pirou",
    "description": "Well-preserved 12th-century castle with triple moats. Long-form companion to the Norman Expansion pin (Normandy).",
    "linkedNodeId": "node-pirou",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Normandy"
    ]
  },
  {
    "slug": "node-palazzo-normanni",
    "title": "Palazzo dei Normanni",
    "description": "Norman seat of power in Sicily, adapted from an Arab palace. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-palazzo-normanni",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-caccamo-castle",
    "title": "Caccamo Castle",
    "description": "One of the largest Norman castles in Italy, perched on a cliff. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-caccamo-castle",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-aci-castello",
    "title": "Aci Castello",
    "description": "Lava-stone fortress on a rocky outcrop above the sea. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-aci-castello",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-erice-castle-of-venus",
    "title": "Castle of Venus, Erice",
    "description": "Norman fortification on the site of an ancient sacred complex. Long-form companion to the Norman Expansion pin (Italy & Sicily).",
    "linkedNodeId": "node-erice-castle-of-venus",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Italy & Sicily"
    ]
  },
  {
    "slug": "node-carrickfergus-castle",
    "title": "Carrickfergus Castle",
    "description": "Best-preserved Norman castle on the island of Ireland. Long-form companion to the Norman Expansion pin (Ireland).",
    "linkedNodeId": "node-carrickfergus-castle",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Ireland"
    ]
  },
  {
    "slug": "node-krak-des-chevaliers",
    "title": "Krak des Chevaliers",
    "description": "One of the most famous Crusader castles in the world. Long-form companion to the Norman Expansion pin (Levant).",
    "linkedNodeId": "node-krak-des-chevaliers",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Levant"
    ]
  },
  {
    "slug": "node-sahyun-saladin-castle",
    "title": "Saône / Saladin Citadel",
    "description": "Byzantine site transformed under Crusader rule with Norman-style keep. Long-form companion to the Norman Expansion pin (Levant).",
    "linkedNodeId": "node-sahyun-saladin-castle",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Levant"
    ]
  },
  {
    "slug": "node-margat-marqab",
    "title": "Marqab Castle",
    "description": "Major fortress within the Principality of Antioch. Long-form companion to the Norman Expansion pin (Levant).",
    "linkedNodeId": "node-margat-marqab",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Levant"
    ]
  },
  {
    "slug": "node-safita-chastel-blanc",
    "title": "Chastel Blanc / Safita",
    "description": "Rectangular keep closely resembling classic Norman tower design. Long-form companion to the Norman Expansion pin (Levant).",
    "linkedNodeId": "node-safita-chastel-blanc",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Levant"
    ]
  },
  {
    "slug": "node-bagras-gaston",
    "title": "Bagras / Gaston",
    "description": "Strategic mountain fortress controlling the Belen Pass. Long-form companion to the Norman Expansion pin (Levant).",
    "linkedNodeId": "node-bagras-gaston",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Levant"
    ]
  },
  {
    "slug": "node-anavarza",
    "title": "Anavarza",
    "description": "Ancient site strengthened by Crusaders with heavy stone defenses. Long-form companion to the Norman Expansion pin (Levant).",
    "linkedNodeId": "node-anavarza",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Levant"
    ]
  },
  {
    "slug": "node-kerak",
    "title": "Kerak Castle",
    "description": "Crusader fortress reflecting Norman and Frankish military traditions. Long-form companion to the Norman Expansion pin (Levant).",
    "linkedNodeId": "node-kerak",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Levant"
    ]
  },
  {
    "slug": "node-mdina-norman",
    "title": "Mdina",
    "description": "Norman-era fortified city; Palazz ta' Santa Sofia and Palazzo Falson survive. Long-form companion to the Norman Expansion pin (Malta).",
    "linkedNodeId": "node-mdina-norman",
    "defaultEraId": "norman-expansion",
    "tags": [
      "Malta"
    ]
  }
];
