import type { AtlasLocale } from '@/core/types';
import { DEFAULT_LOCALE } from '@/lib/locale';

// ---------------------------------------------------------------------------
// Static UI strings — keyed by message id then locale.
// Phase 1: en, fr, es, it.
// ---------------------------------------------------------------------------

type StringTable = Record<string, Partial<Record<AtlasLocale, string>> & { en: string }>;

const STRINGS = {
  // --- Intro / Welcome Gate ---
  'intro.tagline': {
    en: 'A living map of people, movement, and time',
    fr: 'Une carte vivante des peuples, des mouvements et du temps',
    es: 'Un mapa vivo de personas, movimiento y tiempo',
    it: 'Una mappa viva di persone, movimenti e tempo',
  },
  'intro.subtitle': {
    en: 'From the first settlers of Neolithic Normandy\nto the global legacy of the Normans',
    fr: 'Des premiers colons de la Normandie néolithique\nà l\'héritage mondial des Normands',
    es: 'Desde los primeros colonos de la Normandía neolítica\nhasta el legado global de los normandos',
    it: 'Dai primi abitanti della Normandia neolitica\nall\'eredità globale dei Normanni',
  },
  'intro.enter': {
    en: 'Enter Atlas',
    fr: 'Entrer dans l\'Atlas',
    es: 'Entrar al Atlas',
    it: 'Entra nell\'Atlante',
  },
  'intro.normanOverviewLink': {
    en: 'Who were the Normans? Read the overview',
    fr: 'Qui étaient les Normands ? Lire la présentation',
    es: '¿Quiénes fueron los normandos? Leer la introducción',
    it: 'Chi erano i Normanni? Leggi la panoramica',
    de: 'Wer waren die Normannen? Überblick lesen',
    pt: 'Quem foram os normandos? Ler a apresentação',
    da: 'Hvem var normannerne? Læs oversigten',
    nl: 'Wie waren de Normanen? Lees het overzicht',
  },

  // --- Norman overview (modal chrome; body copy: lib/norman-overview/bundles/*.ts) ---
  'normanOverview.sectionLabel': {
    en: 'Historical overview',
    fr: 'Aperçu historique',
    es: 'Panorama histórico',
    it: 'Panoramica storica',
    de: 'Historischer Überblick',
    pt: 'Panorama histórico',
    da: 'Historisk oversigt',
    nl: 'Historisch overzicht',
  },
  'normanOverview.tooltip.label': {
    en: 'Who were the Normans?',
    fr: 'Qui étaient les Normands ?',
    es: '¿Quiénes fueron los normandos?',
    it: 'Chi erano i Normanni?',
    de: 'Wer waren die Normannen?',
    pt: 'Quem foram os normandos?',
    da: 'Hvem var normannerne?',
    nl: 'Wie waren de Normanen?',
  },
  'normanOverview.tooltip.hint': {
    en: 'Timeline context: Celts, Rome, Franks, Vikings, Normandy, and the Norman legacy.',
    fr: 'Contexte de la frise : Celtes, Rome, Francs, Vikings, Normandie et héritage normand.',
    es: 'Contexto de la línea de tiempo: celtas, Roma, francos, vikingos, Normandía y legado normando.',
    it: 'Contesto della cronologia: Celti, Roma, Franchi, Vichinghi, Normandia ed eredità normanna.',
    de: 'Zeitleisten-Kontext: Kelten, Rom, Franken, Wikinger, Normandie und normannisches Erbe.',
    pt: 'Contexto da linha do tempo: celtas, Roma, francos, vikings, Normandia e legado normando.',
    da: 'Tidslinjekontekst: keltere, Rom, frankere, vikinger, Normandiet og normannisk arv.',
    nl: 'Tijdlijncontext: Kelten, Rome, Franken, Vikingen, Normandië en het normannische erfgoed.',
  },
  'normanOverview.aria.open': {
    en: 'Open Norman history overview',
    fr: 'Ouvrir l\'aperçu sur l\'histoire des Normands',
    es: 'Abrir panorama de la historia normanda',
    it: 'Apri la panoramica sulla storia dei Normanni',
    de: 'Normannische Geschichtsübersicht öffnen',
    pt: 'Abrir panorama da história normanda',
    da: 'Åbn oversigt over normannisk historie',
    nl: 'Normannische geschiedenisoverzicht openen',
  },
  'normanOverview.aria.close': {
    en: 'Close overview',
    fr: 'Fermer l\'aperçu',
    es: 'Cerrar panorama',
    it: 'Chiudi panoramica',
    de: 'Überblick schließen',
    pt: 'Fechar panorama',
    da: 'Luk oversigt',
    nl: 'Overzicht sluiten',
  },

  // --- Header chrome ---
  'header.tagline': {
    en: 'A living map of people, movement, and time',
    fr: 'Une carte vivante des peuples, des mouvements et du temps',
    es: 'Un mapa vivo de personas, movimiento y tiempo',
    it: 'Una mappa viva di persone, movimenti e tempo',
  },
  'header.currentEra': {
    en: 'Current Era',
    fr: 'Époque actuelle',
    es: 'Era actual',
    it: 'Era corrente',
  },

  'theme.label': {
    en: 'Interface',
    fr: 'Interface',
    es: 'Interfaz',
    it: 'Interfaccia',
  },
  'theme.aria.dim': {
    en: 'Dim color scheme',
    fr: 'Couleurs tamisées',
    es: 'Esquema de color suave',
    it: 'Schema colori attenuato',
  },
  'theme.aria.bright': {
    en: 'Parchment color scheme',
    fr: 'Couleurs parchemin',
    es: 'Esquema pergamino',
    it: 'Schema colori pergamena',
  },

  'basemap.group': {
    en: 'Map base',
    fr: 'Fond de carte',
    es: 'Base del mapa',
    it: 'Base della mappa',
  },
  'basemap.aria.cartographic': {
    en: 'Cartographic basemap',
    fr: 'Fond cartographique',
    es: 'Mapa cartográfico',
    it: 'Basemap cartografico',
  },
  'basemap.aria.manuscript': {
    en: 'Manuscript-style basemap',
    fr: 'Fond style manuscrit',
    es: 'Mapa estilo manuscrito',
    it: 'Basemap stile manoscritto',
  },

  'terrain.label': {
    en: 'Terrain',
    fr: 'Relief',
    es: 'Relieve',
    it: 'Rilievo',
  },
  'terrain.aria.toggle': {
    en: 'Toggle 3D terrain',
    fr: 'Activer/désactiver le relief 3D',
    es: 'Alternar terreno 3D',
    it: 'Attiva/disattiva terreno 3D',
  },

  'layers.parchmentWater.label': {
    en: 'Sea and atmosphere motion',
    fr: 'Mouvement mer et atmosphère',
    es: 'Movimiento del mar y atmósfera',
    it: 'Movimento di mare e atmosfera',
  },
  'layers.parchmentWater.hint': {
    en: 'Subtle cool drift over the map on manuscript style (not coast-accurate).',
    fr: 'Léger voile froid animé sur la carte (style manuscrit ; pas calé sur les côtes).',
    es: 'Velo frío sutil animado (estilo manuscrito; no coincide con la costa).',
    it: 'Velatura fredda animata sullo stile manoscritto (non allineata alle coste).',
  },

  'layers.explorationYearStrict.label': {
    en: 'Match exploration routes to timeline year',
    fr: 'Aligner les routes d\'exploration sur l\'année de la frise',
    es: 'Alinear rutas de exploración con el año de la línea de tiempo',
    it: 'Allinea le rotte di esplorazione all\'anno della cronologia',
  },
  'layers.explorationYearStrict.hint': {
    en: 'When on, explorer lines only appear if the year slider falls within each segment’s range. When off, all exploration routes for this era stay visible together.',
    fr: 'Activé : les lignes d\'explorateurs n\'apparaissent que si l\'année de la frise tombe dans la plage de chaque segment. Désactivé : toutes les routes d\'exploration de l\'ère restent visibles.',
    es: 'Activado: las líneas solo aparecen si el año cae en el rango de cada tramo. Desactivado: todas las rutas de exploración de la era permanecen visibles.',
    it: 'Attivo: le linee compaiono solo se l\'anno rientra nell\'intervallo di ogni segmento. Spento: tutte le rotte di esplorazione dell\'era restano visibili.',
  },

  // --- Guided tour ---
  'tour.step1.title': {
    en: 'A living historical system',
    fr: 'Un système historique vivant',
    es: 'Un sistema histórico vivo',
    it: 'Un sistema storico vivente',
  },
  'tour.step1.body': {
    en: 'This atlas is not just a map.\nIt shows how people moved, settled, and shaped the world over time — from Neolithic Normandy to the shores of New France.',
    fr: 'Cet atlas n\'est pas une simple carte.\nIl montre comment les peuples se sont déplacés, installés et ont façonné le monde — de la Normandie néolithique aux rives de la Nouvelle-France.',
    es: 'Este atlas no es solo un mapa.\nMuestra cómo las personas se desplazaron, se asentaron y moldearon el mundo — desde la Normandía neolítica hasta las costas de Nueva Francia.',
    it: 'Questo atlante non è solo una mappa.\nMostra come le persone si sono mosse, si sono stabilite e hanno plasmato il mondo — dalla Normandia neolitica alle coste della Nuova Francia.',
  },
  'tour.step2.title': {
    en: 'What you see',
    fr: 'Ce que vous voyez',
    es: 'Lo que verá',
    it: 'Cosa vedi',
  },
  'tour.step2.body': {
    en: 'Each point represents a settlement. Lines trace migration routes. Shaded regions show zones of influence — all reconstructed from available records.',
    fr: 'Chaque point représente un établissement. Les lignes tracent les routes migratoires. Les régions ombrées montrent les zones d\'influence — le tout reconstitué à partir des sources disponibles.',
    es: 'Cada punto representa un asentamiento. Las líneas trazan rutas migratorias. Las regiones sombreadas muestran zonas de influencia, todo reconstruido a partir de registros disponibles.',
    it: 'Ogni punto rappresenta un insediamento. Le linee tracciano rotte migratorie. Le regioni ombreggiate mostrano zone di influenza — tutto ricostruito dalle fonti disponibili.',
  },
  'tour.step3.title': {
    en: 'Navigate through time',
    fr: 'Naviguez dans le temps',
    es: 'Navegue a través del tiempo',
    it: 'Naviga nel tempo',
  },
  'tour.step3.body': {
    en: 'The timeline is the heart of the atlas. Select an era, then drag the year slider to watch history unfold. Each era reveals different migrations, settlements, and layers of activity across the map.',
    fr: 'La frise est le cœur de l\'atlas. Sélectionnez une époque, puis faites glisser le curseur pour voir l\'histoire se dérouler. Chaque ère révèle différentes migrations, établissements et couches d\'activité.',
    es: 'La línea de tiempo es el corazón del atlas. Seleccione una era y arrastre el cursor del año para ver la historia desplegarse. Cada era revela diferentes migraciones, asentamientos y capas de actividad.',
    it: 'La cronologia è il cuore dell\'atlante. Seleziona un\'epoca, poi trascina il cursore dell\'anno per vedere la storia dispiegarsi. Ogni epoca rivela migrazioni, insediamenti e attività diverse.',
  },
  'tour.step4.title': {
    en: 'Cinematic stories',
    fr: 'Histoires cinématiques',
    es: 'Historias cinematográficas',
    it: 'Storie cinematiche',
  },
  'tour.step4.body': {
    en: 'Open the story library to follow curated journeys across the map — from the Viking Age to Norman expansion, New France, and personal histories like Guillaume Couture.\n\nEach arc guides the camera and narrates the events as they happened.',
    fr: 'Ouvrez la bibliothèque pour suivre des parcours guidés sur la carte — de l\'ère viking à l\'expansion normande, la Nouvelle-France et des destins personnels comme Guillaume Couture.\n\nChaque arc guide la caméra et raconte les événements tels qu\'ils se sont déroulés.',
    es: 'Abra la biblioteca de historias para seguir recorridos guiados — desde la era vikinga hasta la expansión normanda, Nueva Francia e historias personales como Guillaume Couture.\n\nCada arco guía la cámara y narra los acontecimientos tal como sucedieron.',
    it: 'Apri la libreria per seguire percorsi guidati sulla mappa — dall\'età vichinga all\'espansione normanna, la Nuova Francia e storie personali come Guillaume Couture.\n\nOgni arco guida la telecamera e racconta gli eventi così come accaddero.',
  },
  'tour.step5.title': {
    en: 'Make it yours',
    fr: 'Personnalisez l\'atlas',
    es: 'Hazlo tuyo',
    it: 'Personalizza l\'atlante',
  },
  'tour.step5.body': {
    en: 'Switch between dark and light mode to change the interface. Toggle the basemap between cartographic and manuscript style for a different feel.\n\nYour preferences are saved automatically.',
    fr: 'Basculez entre mode sombre et clair pour modifier l\'interface. Alternez entre fond cartographique et style manuscrit pour une ambiance différente.\n\nVos préférences sont enregistrées automatiquement.',
    es: 'Alterne entre modo oscuro y claro para cambiar la interfaz. Cambie el mapa base entre estilo cartográfico y manuscrito.\n\nSus preferencias se guardan automáticamente.',
    it: 'Passa tra modalità scura e chiara per modificare l\'interfaccia. Alterna la mappa base tra stile cartografico e manoscritto.\n\nLe tue preferenze vengono salvate automaticamente.',
  },
  'tour.step6.title': {
    en: 'Layers of evidence',
    fr: 'Couches de preuves',
    es: 'Capas de evidencia',
    it: 'Strati di evidenza',
  },
  'tour.step6.body': {
    en: 'Some layers show documented history. Others reveal modeled influence based on historical patterns and scholarly analysis.\n\nClick any location to explore people, events, and context tied to that place and era.',
    fr: 'Certaines couches montrent l\'histoire documentée. D\'autres révèlent l\'influence modélisée à partir de schémas historiques et d\'analyses savantes.\n\nCliquez sur n\'importe quel lieu pour explorer les personnes, les événements et le contexte liés à ce lieu et à cette époque.',
    es: 'Algunas capas muestran historia documentada. Otras revelan influencia modelada a partir de patrones históricos y análisis académicos.\n\nHaga clic en cualquier lugar para explorar personas, eventos y contexto vinculados a ese sitio y esa era.',
    it: 'Alcuni strati mostrano la storia documentata. Altri rivelano un\'influenza modellata su schemi storici e analisi erudite.\n\nClicca su qualsiasi luogo per esplorare persone, eventi e contesto legati a quel posto e a quell\'epoca.',
  },
  'tour.step7.title': {
    en: 'Start your journey',
    fr: 'Commencez votre voyage',
    es: 'Comience su viaje',
    it: 'Inizia il tuo viaggio',
  },
  'tour.step7.body': {
    en: 'Recommended: open the story library and start with "From Vikings to the New World" — the flagship arc covering Norman settlement, expansion, and the Atlantic crossing.\n\nOr explore freely: pick any era from the timeline and follow the map wherever it leads.',
    fr: 'Recommandé : ouvrez la bibliothèque et commencez par « Des Vikings au Nouveau Monde » — l\'arc phare couvrant l\'installation normande, l\'expansion et la traversée de l\'Atlantique.\n\nOu explorez librement : choisissez une époque et suivez la carte où elle vous mène.',
    es: 'Recomendado: abra la biblioteca de historias y comience con «De vikingos al Nuevo Mundo» — el arco principal que cubre el asentamiento normando, la expansión y el cruce del Atlántico.\n\nO explore libremente: elija una era en la línea de tiempo y siga el mapa adonde lo lleve.',
    it: 'Consigliato: apri la libreria e inizia con «Dai vichinghi al Nuovo Mondo» — l\'arco principale su insediamento normanno, espansione e attraversata atlantica.\n\nOppure esplora liberamente: scegli un\'epoca dalla cronologia e segui la mappa ovunque ti porti.',
  },

  // --- Tour controls ---
  'tour.skip': {
    en: 'Skip',
    fr: 'Passer',
    es: 'Omitir',
    it: 'Salta',
  },
  'tour.back': {
    en: 'Back',
    fr: 'Retour',
    es: 'Atrás',
    it: 'Indietro',
  },
  'tour.next': {
    en: 'Next',
    fr: 'Suivant',
    es: 'Siguiente',
    it: 'Avanti',
  },
  'tour.begin': {
    en: 'Begin exploring',
    fr: 'Commencer l\'exploration',
    es: 'Comenzar a explorar',
    it: 'Inizia a esplorare',
  },

  // --- Story bar ---
  'story.explore': {
    en: 'Explore the Story',
    fr: 'Explorer l\'histoire',
    es: 'Explorar la historia',
    it: 'Esplora la storia',
  },
  'story.exit': {
    en: 'Exit story',
    fr: 'Quitter l\'histoire',
    es: 'Salir de la historia',
    it: 'Esci dalla storia',
  },
  'story.continue': {
    en: 'Continue',
    fr: 'Continuer',
    es: 'Continuar',
    it: 'Continua',
  },
  'story.finish': {
    en: 'Finish',
    fr: 'Terminer',
    es: 'Finalizar',
    it: 'Fine',
  },
  'story.illustration.enlarge': {
    en: 'Enlarge image',
    fr: 'Agrandir l\'image',
    es: 'Ampliar imagen',
    it: 'Ingrandisci immagine',
  },
  'story.illustration.close': {
    en: 'Close',
    fr: 'Fermer',
    es: 'Cerrar',
    it: 'Chiudi',
  },

  // --- Story library panel ---
  'storyLibrary.tooltip.label': {
    en: 'Stories',
    fr: 'Histoires',
    es: 'Historias',
    it: 'Storie',
  },
  'storyLibrary.tooltip.hint': {
    en: 'Cinematic story mode: choose an arc, resume, or share a link.',
    fr: 'Mode histoire cinématique : choisir un arc, reprendre ou partager un lien.',
    es: 'Modo historia: elige un arco, reanuda o comparte un enlace.',
    it: 'Modalità storia: scegli un arco, riprendi o condividi un link.',
  },
  'storyLibrary.aria.open': {
    en: 'Open story library',
    fr: 'Ouvrir la bibliothèque d’histoires',
    es: 'Abrir biblioteca de historias',
    it: 'Apri libreria di storie',
  },
  'storyLibrary.aria.close': {
    en: 'Close story library',
    fr: 'Fermer la bibliothèque d’histoires',
    es: 'Cerrar biblioteca de historias',
    it: 'Chiudi libreria di storie',
  },
  'storyLibrary.title': {
    en: 'Story library',
    fr: 'Bibliothèque d’histoires',
    es: 'Biblioteca de historias',
    it: 'Libreria di storie',
  },
  'storyLibrary.subtitle': {
    en: 'Choose a journey across the map',
    fr: 'Choisissez un parcours sur la carte',
    es: 'Elige un recorrido sobre el mapa',
    it: 'Scegli un percorso sulla mappa',
  },
  'storyLibrary.featured': {
    en: 'Featured',
    fr: 'À la une',
    es: 'Destacado',
    it: 'In evidenza',
  },
  'storyLibrary.continueWatching': {
    en: 'Continue watching',
    fr: 'Reprendre la lecture',
    es: 'Continuar viendo',
    it: 'Continua a guardare',
  },
  'storyLibrary.browseByCategory': {
    en: 'Browse by category',
    fr: 'Parcourir par catégorie',
    es: 'Explorar por categoría',
    it: 'Sfoglia per categoria',
  },
  'storyLibrary.play': {
    en: 'Play',
    fr: 'Lire',
    es: 'Reproducir',
    it: 'Riproduci',
  },
  'storyLibrary.resume': {
    en: 'Resume',
    fr: 'Reprendre',
    es: 'Reanudar',
    it: 'Riprendi',
  },
  'storyLibrary.scenes': {
    en: '{count} scenes',
    fr: '{count} scènes',
    es: '{count} escenas',
    it: '{count} scene',
  },
  'storyLibrary.durationMinutes': {
    en: '{count} min',
    fr: '{count} min',
    es: '{count} min',
    it: '{count} min',
  },
  'storyLibrary.chapters': {
    en: 'Chapters',
    fr: 'Chapitres',
    es: 'Capítulos',
    it: 'Capitoli',
  },
  'storyLibrary.copyLink': {
    en: 'Copy link',
    fr: 'Copier le lien',
    es: 'Copiar enlace',
    it: 'Copia link',
  },
  'storyLibrary.linkCopied': {
    en: 'Link copied',
    fr: 'Lien copié',
    es: 'Enlace copiado',
    it: 'Link copiato',
  },
  'storyLibrary.startsInEra': {
    en: 'Starts in: {era}',
    fr: 'Commence à : {era}',
    es: 'Empieza en: {era}',
    it: 'Inizia in: {era}',
  },
  'storyLibrary.progressPercent': {
    en: '{pct}% complete',
    fr: '{pct} % complété',
    es: '{pct} % completo',
    it: '{pct}% completato',
  },
  'storyLibrary.badge.featured': {
    en: 'Featured',
    fr: 'À la une',
    es: 'Destacado',
    it: 'In evidenza',
  },
  'storyLibrary.badge.new': {
    en: 'New',
    fr: 'Nouveau',
    es: 'Nuevo',
    it: 'Nuovo',
  },
  'storyLibrary.badge.inProgress': {
    en: 'In progress',
    fr: 'En cours',
    es: 'En curso',
    it: 'In corso',
  },
  'storyLibrary.badge.completed': {
    en: 'Completed',
    fr: 'Terminé',
    es: 'Completado',
    it: 'Completato',
  },
  'storyLibrary.category.origins': {
    en: 'Origins',
    fr: 'Origines',
    es: 'Orígenes',
    it: 'Origini',
  },
  'storyLibrary.category.conquest': {
    en: 'Conquest',
    fr: 'Conquête',
    es: 'Conquista',
    it: 'Conquista',
  },
  'storyLibrary.category.expansion': {
    en: 'Expansion',
    fr: 'Expansion',
    es: 'Expansión',
    it: 'Espansione',
  },
  'storyLibrary.category.exploration': {
    en: 'Exploration',
    fr: 'Exploration',
    es: 'Exploración',
    it: 'Esplorazione',
  },
  'storyLibrary.category.newFrance': {
    en: 'New France',
    fr: 'Nouvelle-France',
    es: 'Nueva Francia',
    it: 'Nuova Francia',
  },
  'storyLibrary.category.people': {
    en: 'People',
    fr: 'Personnes',
    es: 'Personas',
    it: 'Persone',
  },
  'storyLibrary.category.legacy': {
    en: 'Legacy',
    fr: 'Héritage',
    es: 'Legado',
    it: 'Eredità',
  },

  // --- Credits modal & chrome ---
  'credits.tooltip.label': {
    en: 'Credits & about',
    fr: 'Crédits et à propos',
    es: 'Créditos e información',
    it: 'Crediti e informazioni',
  },
  'credits.tooltip.hint': {
    en: 'Creator, vision, links, and how to support this project.',
    fr: 'Créateur, vision, liens et comment soutenir ce projet.',
    es: 'Creador, visión, enlaces y cómo apoyar este proyecto.',
    it: 'Creatore, visione, link e come sostenere il progetto.',
  },
  'credits.aria.open': {
    en: 'Open credits and about',
    fr: 'Ouvrir les crédits et à propos',
    es: 'Abrir créditos e información',
    it: 'Apri crediti e informazioni',
  },
  'credits.aria.close': {
    en: 'Close credits',
    fr: 'Fermer les crédits',
    es: 'Cerrar créditos',
    it: 'Chiudi crediti',
  },
  'credits.sectionLabel': {
    en: 'Credits',
    fr: 'Crédits',
    es: 'Créditos',
    it: 'Crediti',
  },
  'credits.title': {
    en: 'Created by Guillaume Remi Couture',
    fr: 'Créé par Guillaume Remi Couture',
    es: 'Creado por Guillaume Remi Couture',
    it: 'Creato da Guillaume Remi Couture',
  },
  'credits.intro1': {
    en: 'This atlas was created by Guillaume Remi Couture, a UX/UI designer with nearly two decades of experience building interactive systems, games, and digital products used by millions of people worldwide.',
    fr: 'Cet atlas a été créé par Guillaume Remi Couture, designer UX/UI avec près de vingt ans d\'expérience dans la conception de systèmes interactifs, de jeux et de produits numériques utilisés par des millions de personnes dans le monde.',
    es: 'Este atlas fue creado por Guillaume Remi Couture, diseñador UX/UI con casi dos décadas de experiencia en sistemas interactivos, videojuegos y productos digitales usados por millones de personas en todo el mundo.',
    it: 'Questo atlante è stato creato da Guillaume Remi Couture, designer UX/UI con quasi vent\'anni di esperienza in sistemi interattivi, giochi e prodotti digitali usati da milioni di persone nel mondo.',
  },
  'credits.intro2': {
    en: 'But this project is not just another product.',
    fr: 'Mais ce projet n\'est pas qu\'un produit de plus.',
    es: 'Pero este proyecto no es solo un producto más.',
    it: 'Ma questo progetto non è solo un altro prodotto.',
  },
  'credits.intro3': {
    en: 'It is personal.',
    fr: 'Il est personnel.',
    es: 'Es personal.',
    it: 'È personale.',
  },
  'credits.whyTitle': {
    en: 'Why This Atlas Exists',
    fr: 'Pourquoi cet atlas existe',
    es: 'Por qué existe este atlas',
    it: 'Perché esiste questo atlante',
  },
  'credits.why1': {
    en: 'For as long as I can remember, I have been drawn to the story of the Normans, not just the surface-level version you find in textbooks, but the deeper layers: the movement of people, the migrations, the transformations, the way Viking settlers became one of the most influential forces in medieval Europe.',
    fr: 'Depuis aussi loin que je m\'en souvienne, l\'histoire des Normands m\'a fasciné — pas seulement la version superficielle des manuels, mais les strates profondes : les mouvements de peuples, les migrations, les transformations, la manière dont les colons vikings sont devenus l\'une des forces les plus influentes de l\'Europe médiévale.',
    es: 'Desde que tengo memoria me ha atraído la historia de los normandos, no solo la versión superficial de los libros de texto, sino las capas profundas: el movimiento de gentes, las migraciones, las transformaciones, cómo los colonos vikingos se convirtieron en una de las fuerzas más influyentes de la Europa medieval.',
    it: 'Per quanto mi ricordi, la storia dei Normanni mi ha sempre affascinato — non solo la versione superficiale dei manuali, ma gli strati profondi: il movimento delle genti, le migrazioni, le trasformazioni, come i coloni vichinghi divennero una delle forze più influenti dell\'Europa medievale.',
  },
  'credits.why2': {
    en: 'Normandy is not just a place. It is a turning point. It is where identities shifted, where cultures blended, where something new was created. That ripple effect spread across England, Southern Italy, the Crusader states, and eventually into New France.',
    fr: 'La Normandie n\'est pas qu\'un lieu. C\'est un tournant. C\'est là que les identités se sont déplacées, que les cultures se sont mêlées, que quelque chose de nouveau est né. Cet effet d\'entraînement s\'est propagé en Angleterre, dans le sud de l\'Italie, dans les États des croisades, puis jusqu\'à la Nouvelle-France.',
    es: 'Normandía no es solo un lugar. Es un punto de inflexión. Ahí cambiaron las identidades, se mezclaron las culturas, nació algo nuevo. Ese efecto dominó se extendió por Inglaterra, el sur de Italia, los estados cruzados y, al final, a Nueva Francia.',
    it: 'La Normandia non è solo un luogo. È una svolta. È dove le identità si sono spostate, le culture si sono fuse, è nato qualcosa di nuovo. Quell\'effetto a catena si è diffuso in Inghilterra, nel sud Italia, negli stati crociati e infine nella Nuova Francia.',
  },
  'credits.why3': {
    en: 'But most of this story is fragmented, so I built something to see it clearly.',
    fr: 'Mais la plus grande partie de ce récit est fragmentée — j\'ai donc bâti quelque chose pour le voir clairement.',
    es: 'Pero gran parte de esta historia está fragmentada, así que construí algo para verla con claridad.',
    it: 'Ma gran parte di questa storia è frammentata, così ho costruito qualcosa per vederla con chiarezza.',
  },
  'credits.visionTitle': {
    en: 'The Vision',
    fr: 'La vision',
    es: 'La visión',
    it: 'La visione',
  },
  'credits.visionIntro': {
    en: 'This atlas is meant to be more than a map. It is a living system that lets you:',
    fr: 'Cet atlas veut être bien plus qu\'une carte. C\'est un système vivant qui vous permet de :',
    es: 'Este atlas pretende ser más que un mapa. Es un sistema vivo que le permite:',
    it: 'Questo atlante vuole essere più di una mappa. È un sistema vivente che ti permette di:',
  },
  'credits.visionL1': {
    en: 'Follow migrations across time',
    fr: 'Suivre les migrations dans le temps',
    es: 'Seguir migraciones a lo largo del tiempo',
    it: 'Seguire le migrazioni nel tempo',
  },
  'credits.visionL2': {
    en: 'Explore where people came from and where they settled',
    fr: 'Explorer d\'où venaient les peuples et où ils se sont installés',
    es: 'Explorar de dónde venían las gentes y dónde se asentaron',
    it: 'Esplorare da dove venivano le genti e dove si stabilirono',
  },
  'credits.visionL3': {
    en: 'Understand how cultures evolved',
    fr: 'Comprendre comment les cultures ont évolué',
    es: 'Entender cómo evolucionaron las culturas',
    it: 'Capire come sono evolute le culture',
  },
  'credits.visionL4': {
    en: 'Connect events across centuries in a visual way',
    fr: 'Relier des événements sur des siècles, de façon visuelle',
    es: 'Conectar acontecimientos a lo largo de los siglos de forma visual',
    it: 'Collegare eventi attraverso i secoli in modo visivo',
  },
  'credits.visionOutro': {
    en: 'Instead of reading history in pieces, you can experience it as a continuous story.',
    fr: 'Au lieu de lire l\'histoire par morceaux, vous pouvez la vivre comme un récit continu.',
    es: 'En lugar de leer la historia a trozos, puede vivirla como una narración continua.',
    it: 'Invece di leggere la storia a pezzi, puoi viverla come un racconto continuo.',
  },
  'credits.builtTitle': {
    en: 'Built from Experience',
    fr: 'Construit sur l\'expérience',
    es: 'Construido con experiencia',
    it: 'Costruito sull\'esperienza',
  },
  'credits.builtIntro': {
    en: 'This project brings together everything I have learned over 18+ years in design:',
    fr: 'Ce projet rassemble tout ce que j\'ai appris en plus de 18 ans de design :',
    es: 'Este proyecto reúne todo lo aprendido en más de 18 años de diseño:',
    it: 'Questo progetto riunisce tutto ciò che ho imparato in oltre 18 anni di design:',
  },
  'credits.builtL1': {
    en: 'Game UI and interactive systems',
    fr: 'Interfaces de jeu et systèmes interactifs',
    es: 'IU de juegos y sistemas interactivos',
    it: 'UI di gioco e sistemi interattivi',
  },
  'credits.builtL2': {
    en: 'World-building and spatial storytelling',
    fr: 'Construction de mondes et narration spatiale',
    es: 'Construcción de mundos y narrativa espacial',
    it: 'World-building e narrazione spaziale',
  },
  'credits.builtL3': {
    en: 'UX design for complex systems',
    fr: 'Design UX pour systèmes complexes',
    es: 'Diseño UX para sistemas complejos',
    it: 'Design UX per sistemi complessi',
  },
  'credits.builtL4': {
    en: 'AI-assisted workflows and modern web tech',
    fr: 'Flux de travail assistés par l\'IA et technologies web modernes',
    es: 'Flujos de trabajo con IA y tecnología web moderna',
    it: 'Flussi di lavoro assistiti dall\'IA e tecnologie web moderne',
  },
  'credits.builtOutro': {
    en: 'I have worked with companies like Disney and others, designing experiences meant to guide millions of users. This atlas applies that same thinking to history.',
    fr: 'J\'ai travaillé avec des entreprises comme Disney et d\'autres, en concevant des expériences pour des millions d\'utilisateurs. Cet atlas applique la même démarche à l\'histoire.',
    es: 'He trabajado con empresas como Disney y otras, diseñando experiencias para millones de usuarios. Este atlas aplica la misma idea a la historia.',
    it: 'Ho lavorato con aziende come Disney e altre, progettando esperienze per milioni di utenti. Questo atlante applica lo stesso approccio alla storia.',
  },
  'credits.personalTitle': {
    en: 'A Personal Note',
    fr: 'Une note personnelle',
    es: 'Una nota personal',
    it: 'Una nota personale',
  },
  'credits.personal1': {
    en: 'I am not building this as a traditional historian. I am building this as someone trying to understand where things come from. The Norman story is not just about conquest. It is about identity, movement, and transformation. And in a way, it reflects something deeper about all of us.',
    fr: 'Je ne construis pas cela en historien classique, mais en quelqu\'un qui cherche à comprendre d\'où viennent les choses. L\'histoire normande ne se résume pas à la conquête : elle parle d\'identité, de mouvement, de transformation — et, d\'une certaine façon, de quelque chose de plus profond en nous tous.',
    es: 'No lo construyo como historiador tradicional, sino como alguien que intenta entender de dónde vienen las cosas. La historia normanda no es solo conquista: es identidad, movimiento y transformación — y, en cierto modo, refleja algo más profundo en todos nosotros.',
    it: 'Non lo sto costruendo come storico tradizionale, ma come qualcuno che cerca di capire da dove vengono le cose. La storia normanna non è solo conquista: è identità, movimento, trasformazione — e in un certo senso rispecchia qualcosa di più profondo in ciascuno di noi.',
  },
  'credits.workTitle': {
    en: 'Work With Me',
    fr: 'Travaillons ensemble',
    es: 'Trabajemos juntos',
    it: 'Lavoriamo insieme',
  },
  'credits.workIntro': {
    en: 'If you are interested in working together, collaborating, or bringing this level of design thinking into your own project, connect on LinkedIn:',
    fr: 'Si vous souhaitez collaborer ou intégrer cette approche design à votre projet, contactez-moi sur LinkedIn :',
    es: 'Si le interesa colaborar o llevar este nivel de pensamiento de diseño a su proyecto, conéctese en LinkedIn:',
    it: 'Se vuoi collaborare o portare questo livello di design thinking nel tuo progetto, contattami su LinkedIn:',
  },
  'credits.workAvailable': {
    en: 'I am available for:',
    fr: 'Je suis disponible pour :',
    es: 'Estoy disponible para:',
    it: 'Sono disponibile per:',
  },
  'credits.workL1': {
    en: 'UX/UI design consulting',
    fr: 'Conseil en design UX/UI',
    es: 'Consultoría de diseño UX/UI',
    it: 'Consulenza UX/UI',
  },
  'credits.workL2': {
    en: 'Interactive systems and product design',
    fr: 'Systèmes interactifs et design produit',
    es: 'Sistemas interactivos y diseño de producto',
    it: 'Sistemi interattivi e design di prodotto',
  },
  'credits.workL3': {
    en: 'Game UI/UX',
    fr: 'UI/UX de jeux',
    es: 'UI/UX de videojuegos',
    it: 'UI/UX per giochi',
  },
  'credits.workL4': {
    en: 'AI-assisted workflows and prototyping',
    fr: 'Flux de travail assistés par l\'IA et prototypage',
    es: 'Flujos con IA y prototipado',
    it: 'Flussi assistiti dall\'IA e prototipazione',
  },
  'credits.supportTitle': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostenere l\'Atlante',
  },
  'credits.supportIntro': {
    en: 'Norman Atlas is an independent, long-term historical project. Your support helps fund continued development, research, visual improvements, and new content.',
    fr: 'Norman Atlas est un projet historique indépendant et de long terme. Votre soutien finance le développement continu, la recherche, les améliorations visuelles et les nouveaux contenus.',
    es: 'Norman Atlas es un proyecto histórico independiente a largo plazo. Su apoyo financia el desarrollo continuo, la investigación, las mejoras visuales y los nuevos contenidos.',
    it: 'Norman Atlas è un progetto storico indipendente a lungo termine. Il tuo sostegno finanzia lo sviluppo continuo, la ricerca, i miglioramenti visivi e i nuovi contenuti.',
  },
  'credits.supportCta': {
    en: 'View support options',
    fr: 'Voir les options de soutien',
    es: 'Ver opciones de apoyo',
    it: 'Vedi le opzioni di sostegno',
  },
  'credits.ongoingTitle': {
    en: 'Ongoing Project',
    fr: 'Projet en cours',
    es: 'Proyecto en curso',
    it: 'Progetto in evoluzione',
  },
  'credits.ongoing1': {
    en: 'This atlas is continuously evolving. New eras, deeper historical accuracy, and richer data layers will be added over time. If you are exploring this now, you are early, and that is part of the journey.',
    fr: 'Cet atlas évolue en continu. De nouvelles époques, une meilleure précision historique et des couches de données plus riches seront ajoutées. Si vous explorez cela maintenant, vous êtes en avance — et cela fait partie du parcours.',
    es: 'Este atlas evoluciona sin cesar. Con el tiempo se añadirán nuevas épocas, mayor rigor histórico y capas de datos más ricas. Si lo explora ahora, llega pronto — y eso forma parte del camino.',
    it: 'Questo atlante evolve continuamente. Nel tempo si aggiungeranno nuove epoche, maggiore accuratezza storica e strati di dati più ricchi. Se lo stai esplorando ora sei in anticipo — e fa parte del percorso.',
  },
  // --- Support modal ---
  'support.tooltip.label': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostenere l\'Atlante',
  },
  'support.tooltip.hint': {
    en: 'Help fund future atlas development',
    fr: 'Aidez à financer le développement futur de l\'atlas',
    es: 'Ayude a financiar el desarrollo futuro del atlas',
    it: 'Aiuta a finanziare lo sviluppo futuro dell\'atlante',
  },
  'support.aria.open': {
    en: 'Open support options',
    fr: 'Ouvrir les options de soutien',
    es: 'Abrir opciones de apoyo',
    it: 'Apri le opzioni di sostegno',
  },
  'support.aria.close': {
    en: 'Close support dialog',
    fr: 'Fermer la fenêtre de soutien',
    es: 'Cerrar el diálogo de apoyo',
    it: 'Chiudi la finestra di sostegno',
  },
  'support.headerButton': {
    en: 'Support',
    fr: 'Soutenir',
    es: 'Apoyar',
    it: 'Sostieni',
  },
  'support.headerButtonFull': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostieni l\'Atlante',
  },
  'support.modal.sectionLabel': {
    en: 'Support',
    fr: 'Soutien',
    es: 'Apoyo',
    it: 'Sostegno',
  },
  'support.modal.title': {
    en: 'Support Norman Atlas',
    fr: 'Soutenir Norman Atlas',
    es: 'Apoyar Norman Atlas',
    it: 'Sostenere Norman Atlas',
  },
  'support.modal.body1': {
    en: 'Norman Atlas is an independent historical project built to bring the Norman story to life through maps, timelines, and cinematic exploration.',
    fr: 'Norman Atlas est un projet historique indépendant conçu pour donner vie à l\'histoire normande à travers des cartes, des chronologies et une exploration cinématique.',
    es: 'Norman Atlas es un proyecto histórico independiente creado para dar vida a la historia normanda a través de mapas, cronologías y exploración cinematográfica.',
    it: 'Norman Atlas è un progetto storico indipendente creato per dare vita alla storia normanna attraverso mappe, cronologie ed esplorazione cinematografica.',
  },
  'support.modal.body2': {
    en: 'Your support helps fund continued development, research, new features, and historical expansion.',
    fr: 'Votre soutien finance le développement continu, la recherche, les nouvelles fonctionnalités et l\'expansion historique.',
    es: 'Su apoyo financia el desarrollo continuo, la investigación, nuevas funciones y la expansión histórica.',
    it: 'Il tuo sostegno finanzia lo sviluppo continuo, la ricerca, nuove funzionalità e l\'espansione storica.',
  },
  'support.modal.body3': {
    en: 'If you enjoy the project and want to help it grow, you can support it below.',
    fr: 'Si vous appréciez le projet et souhaitez l\'aider à grandir, vous pouvez le soutenir ci-dessous.',
    es: 'Si disfruta del proyecto y quiere ayudarlo a crecer, puede apoyarlo a continuación.',
    it: 'Se apprezzi il progetto e vuoi aiutarlo a crescere, puoi sostenerlo qui sotto.',
  },
  'support.modal.cta': {
    en: 'Support the Project',
    fr: 'Soutenir le projet',
    es: 'Apoyar el proyecto',
    it: 'Sostieni il progetto',
  },
  'support.mobileDrawer.label': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostenere l\'Atlante',
  },

  // --- Roadmap / what’s next ---
  'roadmap.tooltip.label': {
    en: 'What’s next',
    fr: 'La suite',
    es: 'Qué sigue',
    it: 'Prossimi passi',
  },
  'roadmap.tooltip.hint': {
    en: 'Planned content, Norman diaspora coverage, and upcoming atlas features.',
    fr: 'Contenu prévu, couverture de la diaspora normande et fonctionnalités à venir.',
    es: 'Contenido planeado, la diáspora normanda y funciones futuras del atlas.',
    it: 'Contenuti previsti, diaspora normanna e funzioni in arrivo sull’atlante.',
  },
  'roadmap.aria.open': {
    en: 'Open roadmap and planned updates',
    fr: 'Ouvrir la feuille de route et les mises à jour prévues',
    es: 'Abrir hoja de ruta y actualizaciones previstas',
    it: 'Apri roadmap e aggiornamenti previsti',
  },
  'roadmap.aria.close': {
    en: 'Close roadmap dialog',
    fr: 'Fermer la feuille de route',
    es: 'Cerrar hoja de ruta',
    it: 'Chiudi la finestra della roadmap',
  },
  'roadmap.modal.sectionLabel': {
    en: 'Planned work',
    fr: 'Travaux prévus',
    es: 'Trabajo planeado',
    it: 'Lavoro previsto',
  },
  'roadmap.modal.title': {
    en: 'What we’re building next',
    fr: 'Ce que nous développons ensuite',
    es: 'Qué estamos construyendo',
    it: 'Cosa stiamo costruendo',
  },
  'roadmap.mobileDrawer.label': {
    en: 'What’s next / roadmap',
    fr: 'La suite / feuille de route',
    es: 'Qué sigue / hoja de ruta',
    it: 'Prossimi passi / roadmap',
  },

  'coutureStory.surnameHeading': {
    en: 'The name Couture',
    fr: 'Le nom Couture',
    es: 'El apellido Couture',
    it: 'Il cognome Couture',
  },
  'coutureStory.fullStoryHeading': {
    en: 'His life in full',
    fr: 'Sa vie, en bref',
    es: 'Su vida, en detalle',
    it: 'La sua vita',
  },
  'coutureStory.followMap': {
    en: 'Follow his story on the map',
    fr: 'Suivre son parcours sur la carte',
    es: 'Seguir su historia en el mapa',
    it: 'Segui la sua storia sulla mappa',
  },
  'atlasJournal.tooltip.label': {
    en: 'Atlas Journal',
    fr: 'Journal de l\'Atlas',
    es: 'Diario del Atlas',
    it: 'Diario dell\'Atlante',
  },
  'atlasJournal.tooltip.hint': {
    en: 'Glossary, timeline, Norman names, and how to read the atlas.',
    fr: 'Glossaire, chronologie, patronymes normands et guide de l\'atlas.',
    es: 'Glosario, cronología, apellidos normandos y guía del atlas.',
    it: 'Glossario, cronologia, cognomi normanni e guida dell\'atlante.',
  },
  'atlasJournal.aria.open': {
    en: 'Open atlas journal',
    fr: 'Ouvrir le journal de l\'atlas',
    es: 'Abrir el diario del atlas',
    it: 'Apri il diario dell\'atlante',
  },

  'flythrough.label': {
    en: 'Cinematic Flythrough',
    fr: 'Survol cinématique',
    es: 'Sobrevuelo cinematográfico',
    it: 'Sorvolo cinematico',
  },
  'flythrough.exit': {
    en: 'Exit flythrough',
    fr: 'Quitter le survol',
    es: 'Salir del sobrevuelo',
    it: 'Esci dal sorvolo',
  },
  'flythrough.playing': {
    en: 'Flying along route...',
    fr: 'Survol de la route...',
    es: 'Sobrevolando la ruta...',
    it: 'In volo sulla rotta...',
  },

  // --- Atlas Ledger / Gamification ---
  'ledger.tooltip.label': {
    en: 'Atlas Ledger',
    fr: 'Registre de l\'atlas',
    es: 'Registro del atlas',
    it: 'Registro dell\'atlante',
  },
  'ledger.tooltip.hint': {
    en: 'Your exploration record',
    fr: 'Votre historique d\'exploration',
    es: 'Tu registro de exploración',
    it: 'Il tuo registro di esplorazione',
  },
  'ledger.aria.open': {
    en: 'Open atlas ledger',
    fr: 'Ouvrir le registre de l\'atlas',
    es: 'Abrir el registro del atlas',
    it: 'Apri il registro dell\'atlante',
  },
  'ledger.heading': {
    en: 'Your Atlas Ledger',
    fr: 'Votre registre',
    es: 'Tu registro',
    it: 'Il tuo registro',
  },
  'ledger.coverage': {
    en: 'Coverage',
    fr: 'Couverture',
    es: 'Cobertura',
    it: 'Copertura',
  },
  'ledger.milestones': {
    en: 'Milestones',
    fr: 'Jalons',
    es: 'Hitos',
    it: 'Traguardi',
  },
  'ledger.expeditions': {
    en: 'Expeditions',
    fr: 'Expéditions',
    es: 'Expediciones',
    it: 'Spedizioni',
  },
  'ledger.places': {
    en: 'Places',
    fr: 'Lieux',
    es: 'Lugares',
    it: 'Luoghi',
  },
  'ledger.regions': {
    en: 'Regions',
    fr: 'Régions',
    es: 'Regiones',
    it: 'Regioni',
  },
  'ledger.journeys': {
    en: 'Journeys',
    fr: 'Voyages',
    es: 'Viajes',
    it: 'Viaggi',
  },
  'ledger.segments': {
    en: 'Segments',
    fr: 'Segments',
    es: 'Segmentos',
    it: 'Segmenti',
  },
  'ledger.eras': {
    en: 'Eras explored',
    fr: 'Époques explorées',
    es: 'Épocas exploradas',
    it: 'Epoche esplorate',
  },
  'ledger.stories': {
    en: 'Stories completed',
    fr: 'Récits terminés',
    es: 'Relatos completados',
    it: 'Racconti completati',
  },
  'ledger.empty': {
    en: 'Begin exploring the atlas to fill your ledger.',
    fr: 'Explorez l\'atlas pour remplir votre registre.',
    es: 'Explora el atlas para llenar tu registro.',
    it: 'Esplora l\'atlante per compilare il tuo registro.',
  },
  'ledger.export': {
    en: 'Export progress',
    fr: 'Exporter la progression',
    es: 'Exportar progreso',
    it: 'Esporta progresso',
  },
  'ledger.import': {
    en: 'Import progress',
    fr: 'Importer la progression',
    es: 'Importar progreso',
    it: 'Importa progresso',
  },
  'ledger.reset': {
    en: 'Reset progress',
    fr: 'Réinitialiser',
    es: 'Reiniciar',
    it: 'Reimposta',
  },
  'ledger.reset.confirm': {
    en: 'This will erase all exploration data. Continue?',
    fr: 'Cela effacera toutes les données d\'exploration. Continuer ?',
    es: 'Esto borrará todos los datos de exploración. ¿Continuar?',
    it: 'Questo cancellerà tutti i dati di esplorazione. Continuare?',
  },
  'ledger.role.explorer': {
    en: 'Explorer',
    fr: 'Explorateur',
    es: 'Explorador',
    it: 'Esploratore',
  },
  'ledger.role.historian': {
    en: 'Historian',
    fr: 'Historien',
    es: 'Historiador',
    it: 'Storico',
  },
  'ledger.role.cartographer': {
    en: 'Cartographer',
    fr: 'Cartographe',
    es: 'Cartógrafo',
    it: 'Cartografo',
  },
  'ledger.role.chronicler': {
    en: 'Chronicler',
    fr: 'Chroniqueur',
    es: 'Cronista',
    it: 'Cronista',
  },
  'toast.discovered': {
    en: 'New entry recorded',
    fr: 'Nouvelle entrée enregistrée',
    es: 'Nueva entrada registrada',
    it: 'Nuova voce registrata',
  },
  'toast.milestone': {
    en: 'Milestone reached',
    fr: 'Jalon atteint',
    es: 'Hito alcanzado',
    it: 'Traguardo raggiunto',
  },
  'ledger.mobileDrawer.label': {
    en: 'Atlas Ledger',
    fr: 'Registre',
    es: 'Registro',
    it: 'Registro',
  },
  'expedition.inProgress': {
    en: 'In progress',
    fr: 'En cours',
    es: 'En curso',
    it: 'In corso',
  },
  'expedition.completed': {
    en: 'Completed',
    fr: 'Terminée',
    es: 'Completada',
    it: 'Completata',
  },
  'expedition.start': {
    en: 'Begin expedition',
    fr: 'Commencer l\'expédition',
    es: 'Comenzar expedición',
    it: 'Inizia spedizione',
  },
  'milestone.modal.sealed': {
    en: 'Milestone sealed',
    fr: 'Jalon scellé',
    es: 'Hito sellado',
    it: 'Traguardo sigillato',
  },
  'milestone.modal.continue': {
    en: 'Continue',
    fr: 'Continuer',
    es: 'Continuar',
    it: 'Continua',
  },
  'milestone.modal.share': {
    en: 'Share',
    fr: 'Partager',
    es: 'Compartir',
    it: 'Condividi',
  },
  'milestone.modal.more': {
    en: 'more milestones',
    fr: 'autres jalons',
    es: 'más hitos',
    it: 'altri traguardi',
  },
  'milestone.share.text': {
    en: 'I just unlocked "{title}" on the Norman Atlas!',
    fr: 'Je viens de débloquer « {title} » sur le Norman Atlas !',
    es: '¡Acabo de desbloquear "{title}" en el Norman Atlas!',
    it: 'Ho appena sbloccato "{title}" sul Norman Atlas!',
  },
  'story.seal.recorded': {
    en: 'Arc recorded in your ledger',
    fr: 'Arc enregistré dans votre registre',
    es: 'Arco registrado en tu registro',
    it: 'Arco registrato nel tuo registro',
  },
  'expedition.chip.progress': {
    en: '{done}/{total}',
    fr: '{done}/{total}',
    es: '{done}/{total}',
    it: '{done}/{total}',
  },
  'story.seal.subtitle': {
    en: 'Your progress has been saved in the Atlas Ledger.',
    fr: 'Votre progression a été enregistrée dans le registre de l\'atlas.',
    es: 'Tu progreso se ha guardado en el registro del atlas.',
    it: 'I tuoi progressi sono stati salvati nel registro dell\'atlante.',
  },
  'ledger.affordance.mobile': {
    en: 'Open Ledger',
    fr: 'Ouvrir le registre',
    es: 'Abrir registro',
    it: 'Apri registro',
  },
} as const satisfies StringTable;

export type UiStringKey = keyof typeof STRINGS;

/**
 * Look up a UI string by key and locale, falling back to English.
 */
export function t(key: UiStringKey, locale: AtlasLocale): string {
  const entry = STRINGS[key];
  return (entry as Record<string, string | undefined>)[locale] ?? entry.en;
}
