import type { AtlasLocale } from '@/core/types';
import { DEFAULT_LOCALE } from '@/lib/locale';

// ---------------------------------------------------------------------------
// Static UI strings, keyed by message id then locale.
// Phase 1: en, fr, es, it.
// ---------------------------------------------------------------------------

type StringTable = Record<string, Partial<Record<AtlasLocale, string>> & { en: string }>;

const STRINGS = {
  // --- Intro / Welcome Gate ---
  'intro.tagline': {
    en: 'A living map of people, movement, and time',
    fr: 'Une carte vivante des peuples, des mouvements et du temps',
    es: 'Un mapa vivo de personas, movimiento y tiempo',
    it: 'Una mappa viva di persone, movimenti e tempo',
  },
  'intro.subtitle': {
    en: 'From the first settlers of Neolithic Normandy\nto the global legacy of the Normans',
    fr: 'Des premiers colons de la Normandie néolithique\nà l\'héritage mondial des Normands',
    es: 'Desde los primeros colonos de la Normandía neolítica\nhasta el legado global de los normandos',
    it: 'Dai primi abitanti della Normandia neolitica\nall\'eredità globale dei Normanni',
  },
  'intro.enter': {
    en: 'Enter Atlas',
    fr: 'Entrer dans l\'Atlas',
    es: 'Entrar al Atlas',
    it: 'Entra nell\'Atlante',
  },
  'intro.normanOverviewLink': {
    en: 'Who were the Normans? Read the overview',
    fr: 'Qui étaient les Normands ? Lire la présentation',
    es: '¿Quiénes fueron los normandos? Leer la introducción',
    it: 'Chi erano i Normanni? Leggi la panoramica',
    de: 'Wer waren die Normannen? Überblick lesen',
    pt: 'Quem foram os normandos? Ler a apresentação',
    da: 'Hvem var normannerne? Læs oversigten',
    nl: 'Wie waren de Normanen? Lees het overzicht',
  },

  // --- Norman overview (modal chrome; body copy: lib/norman-overview/bundles/*.ts) ---
  'normanOverview.sectionLabel': {
    en: 'Historical overview',
    fr: 'Aperçu historique',
    es: 'Panorama histórico',
    it: 'Panoramica storica',
    de: 'Historischer Überblick',
    pt: 'Panorama histórico',
    da: 'Historisk oversigt',
    nl: 'Historisch overzicht',
  },
  'normanOverview.tooltip.label': {
    en: 'Who were the Normans?',
    fr: 'Qui étaient les Normands ?',
    es: '¿Quiénes fueron los normandos?',
    it: 'Chi erano i Normanni?',
    de: 'Wer waren die Normannen?',
    pt: 'Quem foram os normandos?',
    da: 'Hvem var normannerne?',
    nl: 'Wie waren de Normanen?',
  },
  'normanOverview.tooltip.hint': {
    en: 'Timeline context: Celts, Rome, Franks, Vikings, Normandy, and the Norman legacy.',
    fr: 'Contexte de la frise : Celtes, Rome, Francs, Vikings, Normandie et héritage normand.',
    es: 'Contexto de la línea de tiempo: celtas, Roma, francos, vikingos, Normandía y legado normando.',
    it: 'Contesto della cronologia: Celti, Roma, Franchi, Vichinghi, Normandia ed eredità normanna.',
    de: 'Zeitleisten-Kontext: Kelten, Rom, Franken, Wikinger, Normandie und normannisches Erbe.',
    pt: 'Contexto da linha do tempo: celtas, Roma, francos, vikings, Normandia e legado normando.',
    da: 'Tidslinjekontekst: keltere, Rom, frankere, vikinger, Normandiet og normannisk arv.',
    nl: 'Tijdlijncontext: Kelten, Rome, Franken, Vikingen, Normandië en het normannische erfgoed.',
  },
  'normanOverview.aria.open': {
    en: 'Open Norman history overview',
    fr: 'Ouvrir l\'aperçu sur l\'histoire des Normands',
    es: 'Abrir panorama de la historia normanda',
    it: 'Apri la panoramica sulla storia dei Normanni',
    de: 'Normannische Geschichtsübersicht öffnen',
    pt: 'Abrir panorama da história normanda',
    da: 'Åbn oversigt over normannisk historie',
    nl: 'Normannische geschiedenisoverzicht openen',
  },
  'normanOverview.aria.close': {
    en: 'Close overview',
    fr: 'Fermer l\'aperçu',
    es: 'Cerrar panorama',
    it: 'Chiudi panoramica',
    de: 'Überblick schließen',
    pt: 'Fechar panorama',
    da: 'Luk oversigt',
    nl: 'Overzicht sluiten',
  },

  // --- Header chrome ---
  'header.tagline': {
    en: 'A living map of people, movement, and time',
    fr: 'Une carte vivante des peuples, des mouvements et du temps',
    es: 'Un mapa vivo de personas, movimiento y tiempo',
    it: 'Una mappa viva di persone, movimenti e tempo',
  },
  'header.currentEra': {
    en: 'Current Era',
    fr: 'Époque actuelle',
    es: 'Era actual',
    it: 'Era corrente',
  },

  'theme.label': {
    en: 'Interface',
    fr: 'Interface',
    es: 'Interfaz',
    it: 'Interfaccia',
  },
  'theme.aria.dim': {
    en: 'Dim color scheme',
    fr: 'Couleurs tamisées',
    es: 'Esquema de color suave',
    it: 'Schema colori attenuato',
  },
  'theme.aria.bright': {
    en: 'Parchment color scheme',
    fr: 'Couleurs parchemin',
    es: 'Esquema pergamino',
    it: 'Schema colori pergamena',
  },

  'textSize.tooltip.label': {
    en: 'Adjust text size',
    fr: 'Taille du texte',
    es: 'Tamaño del texto',
    it: 'Dimensione del testo',
  },
  'textSize.tooltip.hint': {
    en: 'Improve readability',
    fr: 'Améliorer la lisibilité',
    es: 'Mejorar la legibilidad',
    it: 'Migliora la leggibilità',
  },
  'textSize.standard': {
    en: 'Standard text',
    fr: 'Texte standard',
    es: 'Texto estándar',
    it: 'Testo standard',
  },
  'textSize.large': {
    en: 'Large text',
    fr: 'Grand texte',
    es: 'Texto grande',
    it: 'Testo grande',
  },
  'textSize.highContrast': {
    en: 'High contrast (coming soon)',
    fr: 'Contraste élevé (bientôt)',
    es: 'Alto contraste (próximamente)',
    it: 'Alto contrasto (in arrivo)',
  },
  'textSize.reducedMotion': {
    en: 'Reduced motion (coming soon)',
    fr: 'Mouvement réduit (bientôt)',
    es: 'Movimiento reducido (próximamente)',
    it: 'Movimento ridotto (in arrivo)',
  },

  'basemap.group': {
    en: 'Map base',
    fr: 'Fond de carte',
    es: 'Base del mapa',
    it: 'Base della mappa',
  },
  'basemap.aria.cartographic': {
    en: 'Cartographic basemap',
    fr: 'Fond cartographique',
    es: 'Mapa cartográfico',
    it: 'Basemap cartografico',
  },
  'basemap.aria.manuscript': {
    en: 'Manuscript-style basemap',
    fr: 'Fond style manuscrit',
    es: 'Mapa estilo manuscrito',
    it: 'Basemap stile manoscritto',
  },

  'terrain.label': {
    en: 'Terrain',
    fr: 'Relief',
    es: 'Relieve',
    it: 'Rilievo',
  },
  'terrain.aria.toggle': {
    en: 'Toggle 3D terrain',
    fr: 'Activer/désactiver le relief 3D',
    es: 'Alternar terreno 3D',
    it: 'Attiva/disattiva terreno 3D',
  },

  'layers.parchmentWater.label': {
    en: 'Sea and atmosphere motion',
    fr: 'Mouvement mer et atmosphère',
    es: 'Movimiento del mar y atmósfera',
    it: 'Movimento di mare e atmosfera',
  },
  'layers.parchmentWater.hint': {
    en: 'Subtle cool drift over the map on manuscript style (not coast-accurate).',
    fr: 'Léger voile froid animé sur la carte (style manuscrit ; pas calé sur les côtes).',
    es: 'Velo frío sutil animado (estilo manuscrito; no coincide con la costa).',
    it: 'Velatura fredda animata sullo stile manoscritto (non allineata alle coste).',
  },

  'layers.explorationYearStrict.label': {
    en: 'Match exploration routes to timeline year',
    fr: 'Aligner les routes d\'exploration sur l\'année de la frise',
    es: 'Alinear rutas de exploración con el año de la línea de tiempo',
    it: 'Allinea le rotte di esplorazione all\'anno della cronologia',
  },
  'layers.explorationYearStrict.hint': {
    en: 'When on, explorer lines only appear if the year slider falls within each segment’s range. When off, all exploration routes for this era stay visible together.',
    fr: 'Activé : les lignes d\'explorateurs n\'apparaissent que si l\'année de la frise tombe dans la plage de chaque segment. Désactivé : toutes les routes d\'exploration de l\'ère restent visibles.',
    es: 'Activado: las líneas solo aparecen si el año cae en el rango de cada tramo. Desactivado: todas las rutas de exploración de la era permanecen visibles.',
    it: 'Attivo: le linee compaiono solo se l\'anno rientra nell\'intervallo di ogni segmento. Spento: tutte le rotte di esplorazione dell\'era restano visibili.',
  },

  // --- Guided tour ---
  'tour.step1.title': {
    en: 'A living historical system',
    fr: 'Un système historique vivant',
    es: 'Un sistema histórico vivo',
    it: 'Un sistema storico vivente',
  },
  'tour.step1.body': {
    en: 'This atlas is not just a map.\nIt shows how people moved, settled, and shaped the world over time, from Neolithic Normandy to the shores of New France.',
    fr: 'Cet atlas n\'est pas une simple carte.\nIl montre comment les peuples se sont déplacés, installés et ont façonné le monde, de la Normandie néolithique aux rives de la Nouvelle-France.',
    es: 'Este atlas no es solo un mapa.\nMuestra cómo las personas se desplazaron, se asentaron y moldearon el mundo, desde la Normandía neolítica hasta las costas de Nueva Francia.',
    it: 'Questo atlante non è solo una mappa.\nMostra come le persone si sono mosse, si sono stabilite e hanno plasmato il mondo, dalla Normandia neolitica alle coste della Nuova Francia.',
  },
  'tour.step2.title': {
    en: 'What you see',
    fr: 'Ce que vous voyez',
    es: 'Lo que verá',
    it: 'Cosa vedi',
  },
  'tour.step2.body': {
    en: 'Each point represents a settlement. Lines trace migration routes. Shaded regions show zones of influence, all reconstructed from available records.',
    fr: 'Chaque point représente un établissement. Les lignes tracent les routes migratoires. Les régions ombrées montrent les zones d\'influence, le tout reconstitué à partir des sources disponibles.',
    es: 'Cada punto representa un asentamiento. Las líneas trazan rutas migratorias. Las regiones sombreadas muestran zonas de influencia, todo reconstruido a partir de registros disponibles.',
    it: 'Ogni punto rappresenta un insediamento. Le linee tracciano rotte migratorie. Le regioni ombreggiate mostrano zone di influenza, tutto ricostruito dalle fonti disponibili.',
  },
  'tour.step3.title': {
    en: 'Navigate through time',
    fr: 'Naviguez dans le temps',
    es: 'Navegue a través del tiempo',
    it: 'Naviga nel tempo',
  },
  'tour.step3.body': {
    en: 'The timeline is the heart of the atlas. Select an era, then drag the year slider to watch history unfold. Each era reveals different migrations, settlements, and layers of activity across the map.',
    fr: 'La frise est le cœur de l\'atlas. Sélectionnez une époque, puis faites glisser le curseur pour voir l\'histoire se dérouler. Chaque ère révèle différentes migrations, établissements et couches d\'activité.',
    es: 'La línea de tiempo es el corazón del atlas. Seleccione una era y arrastre el cursor del año para ver la historia desplegarse. Cada era revela diferentes migraciones, asentamientos y capas de actividad.',
    it: 'La cronologia è il cuore dell\'atlante. Seleziona un\'epoca, poi trascina il cursore dell\'anno per vedere la storia dispiegarsi. Ogni epoca rivela migrazioni, insediamenti e attività diverse.',
  },
  'tour.step4.title': {
    en: 'Cinematic stories',
    fr: 'Histoires cinématiques',
    es: 'Historias cinematográficas',
    it: 'Storie cinematiche',
  },
  'tour.step4.body': {
    en: 'Open the story library to follow curated journeys across the map, from the Viking Age to Norman expansion, New France, and personal histories like Guillaume Couture.\n\nEach arc guides the camera and narrates the events as they happened.',
    fr: 'Ouvrez la bibliothèque pour suivre des parcours guidés sur la carte, de l\'ère viking à l\'expansion normande, la Nouvelle-France et des destins personnels comme Guillaume Couture.\n\nChaque arc guide la caméra et raconte les événements tels qu\'ils se sont déroulés.',
    es: 'Abra la biblioteca de historias para seguir recorridos guiados, desde la era vikinga hasta la expansión normanda, Nueva Francia e historias personales como Guillaume Couture.\n\nCada arco guía la cámara y narra los acontecimientos tal como sucedieron.',
    it: 'Apri la libreria per seguire percorsi guidati sulla mappa, dall\'età vichinga all\'espansione normanna, la Nuova Francia e storie personali come Guillaume Couture.\n\nOgni arco guida la telecamera e racconta gli eventi così come accaddero.',
  },
  'tour.step5.title': {
    en: 'Make it yours',
    fr: 'Personnalisez l\'atlas',
    es: 'Hazlo tuyo',
    it: 'Personalizza l\'atlante',
  },
  'tour.step5.body': {
    en: 'Switch between dark and light mode to change the interface. Toggle the basemap between cartographic and manuscript style for a different feel.\n\nYour preferences are saved automatically.',
    fr: 'Basculez entre mode sombre et clair pour modifier l\'interface. Alternez entre fond cartographique et style manuscrit pour une ambiance différente.\n\nVos préférences sont enregistrées automatiquement.',
    es: 'Alterne entre modo oscuro y claro para cambiar la interfaz. Cambie el mapa base entre estilo cartográfico y manuscrito.\n\nSus preferencias se guardan automáticamente.',
    it: 'Passa tra modalità scura e chiara per modificare l\'interfaccia. Alterna la mappa base tra stile cartografico e manoscritto.\n\nLe tue preferenze vengono salvate automaticamente.',
  },
  'tour.step6.title': {
    en: 'Layers of evidence',
    fr: 'Couches de preuves',
    es: 'Capas de evidencia',
    it: 'Strati di evidenza',
  },
  'tour.step6.body': {
    en: 'Some layers show documented history. Others reveal modeled influence based on historical patterns and scholarly analysis.\n\nClick any location to explore people, events, and context tied to that place and era.',
    fr: 'Certaines couches montrent l\'histoire documentée. D\'autres révèlent l\'influence modélisée à partir de schémas historiques et d\'analyses savantes.\n\nCliquez sur n\'importe quel lieu pour explorer les personnes, les événements et le contexte liés à ce lieu et à cette époque.',
    es: 'Algunas capas muestran historia documentada. Otras revelan influencia modelada a partir de patrones históricos y análisis académicos.\n\nHaga clic en cualquier lugar para explorar personas, eventos y contexto vinculados a ese sitio y esa era.',
    it: 'Alcuni strati mostrano la storia documentata. Altri rivelano un\'influenza modellata su schemi storici e analisi erudite.\n\nClicca su qualsiasi luogo per esplorare persone, eventi e contesto legati a quel posto e a quell\'epoca.',
  },
  'tour.step7.title': {
    en: 'Start your journey',
    fr: 'Commencez votre voyage',
    es: 'Comience su viaje',
    it: 'Inizia il tuo viaggio',
  },
  'tour.step7.body': {
    en: 'Recommended: open the story library and start with "From Vikings to the New World." The flagship arc covers Norman settlement, expansion, and the Atlantic crossing.\n\nOr explore freely: pick any era from the timeline and follow the map wherever it leads.',
    fr: 'Recommandé : ouvrez la bibliothèque et commencez par « Des Vikings au Nouveau Monde ». L\'arc phare couvre l\'installation normande, l\'expansion et la traversée de l\'Atlantique.\n\nOu explorez librement : choisissez une époque et suivez la carte où elle vous mène.',
    es: 'Recomendado: abra la biblioteca de historias y comience con «De vikingos al Nuevo Mundo». El arco principal cubre el asentamiento normando, la expansión y el cruce del Atlántico.\n\nO explore libremente: elija una era en la línea de tiempo y siga el mapa adonde lo lleve.',
    it: 'Consigliato: apri la libreria e inizia con «Dai vichinghi al Nuovo Mondo». L\'arco principale riguarda insediamento normanno, espansione e attraversata atlantica.\n\nOppure esplora liberamente: scegli un\'epoca dalla cronologia e segui la mappa ovunque ti porti.',
  },

  // --- Tour controls ---
  'tour.skip': {
    en: 'Skip',
    fr: 'Passer',
    es: 'Omitir',
    it: 'Salta',
  },
  'tour.back': {
    en: 'Back',
    fr: 'Retour',
    es: 'Atrás',
    it: 'Indietro',
  },
  'tour.next': {
    en: 'Next',
    fr: 'Suivant',
    es: 'Siguiente',
    it: 'Avanti',
  },
  'tour.begin': {
    en: 'Begin exploring',
    fr: 'Commencer l\'exploration',
    es: 'Comenzar a explorar',
    it: 'Inizia a esplorare',
  },

  // --- Story bar ---
  'story.explore': {
    en: 'Explore the Story',
    fr: 'Explorer l\'histoire',
    es: 'Explorar la historia',
    it: 'Esplora la storia',
  },
  'story.exit': {
    en: 'Exit story',
    fr: 'Quitter l\'histoire',
    es: 'Salir de la historia',
    it: 'Esci dalla storia',
  },
  'story.continue': {
    en: 'Continue',
    fr: 'Continuer',
    es: 'Continuar',
    it: 'Continua',
  },
  'story.finish': {
    en: 'Finish',
    fr: 'Terminer',
    es: 'Finalizar',
    it: 'Fine',
  },
  'story.illustration.enlarge': {
    en: 'Enlarge image',
    fr: 'Agrandir l\'image',
    es: 'Ampliar imagen',
    it: 'Ingrandisci immagine',
  },
  'story.illustration.close': {
    en: 'Close',
    fr: 'Fermer',
    es: 'Cerrar',
    it: 'Chiudi',
  },

  // --- Story library panel ---
  'storyLibrary.tooltip.label': {
    en: 'Stories',
    fr: 'Histoires',
    es: 'Historias',
    it: 'Storie',
  },
  'storyLibrary.tooltip.hint': {
    en: 'Cinematic story mode: choose an arc, resume, or share a link.',
    fr: 'Mode histoire cinématique : choisir un arc, reprendre ou partager un lien.',
    es: 'Modo historia: elige un arco, reanuda o comparte un enlace.',
    it: 'Modalità storia: scegli un arco, riprendi o condividi un link.',
  },
  'storyLibrary.aria.open': {
    en: 'Open story library',
    fr: 'Ouvrir la bibliothèque d’histoires',
    es: 'Abrir biblioteca de historias',
    it: 'Apri libreria di storie',
  },
  'storyLibrary.aria.close': {
    en: 'Close story library',
    fr: 'Fermer la bibliothèque d’histoires',
    es: 'Cerrar biblioteca de historias',
    it: 'Chiudi libreria di storie',
  },
  'storyLibrary.aria.heroCarouselStrip': {
    en: 'Featured story previews',
    fr: 'Aperçus des histoires à la une',
    es: 'Vistas previas destacadas',
    it: 'Anteprime in evidenza',
  },
  'storyLibrary.aria.heroSegment': {
    en: 'Show featured story {n} of {total}',
    fr: 'Afficher l’histoire à la une {n} sur {total}',
    es: 'Mostrar historia destacada {n} de {total}',
    it: 'Mostra storia in evidenza {n} di {total}',
  },
  'storyLibrary.title': {
    en: 'Story library',
    fr: 'Bibliothèque d’histoires',
    es: 'Biblioteca de historias',
    it: 'Libreria di storie',
  },
  'storyLibrary.subtitle': {
    en: 'Choose a journey across the map',
    fr: 'Choisissez un parcours sur la carte',
    es: 'Elige un recorrido sobre el mapa',
    it: 'Scegli un percorso sulla mappa',
  },
  'storyLibrary.featured': {
    en: 'Featured',
    fr: 'À la une',
    es: 'Destacado',
    it: 'In evidenza',
  },
  'storyLibrary.continueWatching': {
    en: 'Continue watching',
    fr: 'Reprendre la lecture',
    es: 'Continuar viendo',
    it: 'Continua a guardare',
  },
  'storyLibrary.browseByCategory': {
    en: 'Browse by category',
    fr: 'Parcourir par catégorie',
    es: 'Explorar por categoría',
    it: 'Sfoglia per categoria',
  },
  'storyLibrary.play': {
    en: 'Play',
    fr: 'Lire',
    es: 'Reproducir',
    it: 'Riproduci',
  },
  'storyLibrary.resume': {
    en: 'Resume',
    fr: 'Reprendre',
    es: 'Reanudar',
    it: 'Riprendi',
  },
  'storyLibrary.scenes': {
    en: '{count} scenes',
    fr: '{count} scènes',
    es: '{count} escenas',
    it: '{count} scene',
  },
  'storyLibrary.durationMinutes': {
    en: '{count} min',
    fr: '{count} min',
    es: '{count} min',
    it: '{count} min',
  },
  'storyLibrary.chapters': {
    en: 'Chapters',
    fr: 'Chapitres',
    es: 'Capítulos',
    it: 'Capitoli',
  },
  'storyLibrary.copyLink': {
    en: 'Copy link',
    fr: 'Copier le lien',
    es: 'Copiar enlace',
    it: 'Copia link',
  },
  'storyLibrary.linkCopied': {
    en: 'Link copied',
    fr: 'Lien copié',
    es: 'Enlace copiado',
    it: 'Link copiato',
  },
  'storyLibrary.startsInEra': {
    en: 'Starts in: {era}',
    fr: 'Commence à : {era}',
    es: 'Empieza en: {era}',
    it: 'Inizia in: {era}',
  },
  'storyLibrary.progressPercent': {
    en: '{pct}% complete',
    fr: '{pct} % complété',
    es: '{pct} % completo',
    it: '{pct}% completato',
  },
  'storyLibrary.badge.featured': {
    en: 'Featured',
    fr: 'À la une',
    es: 'Destacado',
    it: 'In evidenza',
  },
  'storyLibrary.badge.new': {
    en: 'New',
    fr: 'Nouveau',
    es: 'Nuevo',
    it: 'Nuovo',
  },
  'storyLibrary.badge.inProgress': {
    en: 'In progress',
    fr: 'En cours',
    es: 'En curso',
    it: 'In corso',
  },
  'storyLibrary.badge.completed': {
    en: 'Completed',
    fr: 'Terminé',
    es: 'Completado',
    it: 'Completato',
  },
  'storyLibrary.category.origins': {
    en: 'Origins',
    fr: 'Origines',
    es: 'Orígenes',
    it: 'Origini',
  },
  'storyLibrary.category.conquest': {
    en: 'Conquest',
    fr: 'Conquête',
    es: 'Conquista',
    it: 'Conquista',
  },
  'storyLibrary.category.expansion': {
    en: 'Expansion',
    fr: 'Expansion',
    es: 'Expansión',
    it: 'Espansione',
  },
  'storyLibrary.category.exploration': {
    en: 'Exploration',
    fr: 'Exploration',
    es: 'Exploración',
    it: 'Esplorazione',
  },
  'storyLibrary.category.newFrance': {
    en: 'New France',
    fr: 'Nouvelle-France',
    es: 'Nueva Francia',
    it: 'Nuova Francia',
  },
  'storyLibrary.category.people': {
    en: 'People',
    fr: 'Personnes',
    es: 'Personas',
    it: 'Persone',
  },
  'storyLibrary.category.legacy': {
    en: 'Legacy',
    fr: 'Héritage',
    es: 'Legado',
    it: 'Eredità',
  },
  'storyLibrary.moreInfo': {
    en: 'More info',
    fr: 'Plus d\'infos',
    es: 'Más información',
    it: 'Più info',
  },
  'storyLibrary.tone.epic': {
    en: 'Epic',
    fr: 'Épique',
    es: 'Épico',
    it: 'Epico',
  },
  'storyLibrary.tone.dark': {
    en: 'Dark',
    fr: 'Sombre',
    es: 'Oscuro',
    it: 'Cupo',
  },
  'storyLibrary.tone.exploratory': {
    en: 'Exploratory',
    fr: 'Exploratoire',
    es: 'Exploratorio',
    it: 'Esplorativo',
  },
  'storyLibrary.tone.foundational': {
    en: 'Foundational',
    fr: 'Fondateur',
    es: 'Fundacional',
    it: 'Fondativo',
  },
  'storyLibrary.tone.personal': {
    en: 'Personal',
    fr: 'Personnel',
    es: 'Personal',
    it: 'Personale',
  },
  'storyLibrary.timelineRange': {
    en: '{start} – {end}',
    fr: '{start} – {end}',
    es: '{start} – {end}',
    it: '{start} – {end}',
  },
  'storyLibrary.focusPlaces': {
    en: '{count} places',
    fr: '{count} lieux',
    es: '{count} lugares',
    it: '{count} luoghi',
  },
  'storyLibrary.focusRegions': {
    en: '{count} regions',
    fr: '{count} régions',
    es: '{count} regiones',
    it: '{count} regioni',
  },
  'storyLibrary.focusRoutes': {
    en: '{count} routes',
    fr: '{count} routes',
    es: '{count} rutas',
    it: '{count} rotte',
  },
  'storyLibrary.imageCredit': {
    en: 'Image: {credit}',
    fr: 'Image : {credit}',
    es: 'Imagen: {credit}',
    it: 'Immagine: {credit}',
  },
  'storyLibrary.section.overview': {
    en: 'Overview',
    fr: 'Aperçu',
    es: 'Resumen',
    it: 'Panoramica',
  },
  'storyLibrary.section.details': {
    en: 'Details',
    fr: 'Détails',
    es: 'Detalles',
    it: 'Dettagli',
  },
  'storyLibrary.section.chapters': {
    en: 'Chapters',
    fr: 'Chapitres',
    es: 'Capítulos',
    it: 'Capitoli',
  },
  'storyLibrary.showMore': {
    en: 'Show all',
    fr: 'Tout afficher',
    es: 'Mostrar todo',
    it: 'Mostra tutto',
  },
  'storyLibrary.showLess': {
    en: 'Show less',
    fr: 'Réduire',
    es: 'Mostrar menos',
    it: 'Mostra meno',
  },
  'storyLibrary.aria.scrollLeft': {
    en: 'Scroll left',
    fr: 'Défiler à gauche',
    es: 'Desplazar a la izquierda',
    it: 'Scorri a sinistra',
  },
  'storyLibrary.aria.scrollRight': {
    en: 'Scroll right',
    fr: 'Défiler à droite',
    es: 'Desplazar a la derecha',
    it: 'Scorri a destra',
  },
  'storyLibrary.aria.heroCarousel': {
    en: 'Featured stories rotate automatically; hover to pause.',
    fr: 'Les histoires à la une défilent automatiquement ; survolez pour mettre en pause.',
    es: 'Las historias destacadas rotan solas; pasa el cursor para pausar.',
    it: 'Le storie in evidenza scorrono automaticamente; passa sopra per mettere in pausa.',
  },
  'storyLibrary.chronicle.title': {
    en: 'Choose Your Chronicle',
    fr: 'Choisissez votre chronique',
    es: 'Elige tu crónica',
    it: 'Scegli la tua cronaca',
  },
  'storyLibrary.beginJourney': {
    en: 'Begin Journey',
    fr: 'Commencer le parcours',
    es: 'Comenzar el viaje',
    it: 'Inizia il viaggio',
  },
  'storyLibrary.viewChapters': {
    en: 'View Chapters',
    fr: 'Voir les chapitres',
    es: 'Ver capítulos',
    it: 'Vedi i capitoli',
  },
  'storyLibrary.filter.all': {
    en: 'All',
    fr: 'Tout',
    es: 'Todo',
    it: 'Tutto',
  },
  'storyLibrary.filter.allEras': {
    en: 'All eras',
    fr: 'Toutes les ères',
    es: 'Todas las eras',
    it: 'Tutte le epoche',
  },
  'storyLibrary.aria.filterBar': {
    en: 'Filter stories by category',
    fr: 'Filtrer les histoires par catégorie',
    es: 'Filtrar historias por categoría',
    it: 'Filtra le storie per categoria',
  },
  'storyLibrary.aria.eraFilterBar': {
    en: 'Filter stories by historical era',
    fr: 'Filtrer les histoires par ère historique',
    es: 'Filtrar historias por época histórica',
    it: 'Filtra le storie per epoca storica',
  },
  'storyLibrary.backToMap': {
    en: 'Back to map',
    fr: 'Retour à la carte',
    es: 'Volver al mapa',
    it: 'Torna alla mappa',
  },
  'storyLibrary.searchPlaceholder': {
    en: 'Search chronicles',
    fr: 'Rechercher dans les chroniques',
    es: 'Buscar crónicas',
    it: 'Cerca nelle cronache',
  },
  'storyLibrary.searchAria': {
    en: 'Search stories by title or description',
    fr: 'Rechercher des histoires par titre ou description',
    es: 'Buscar historias por título o descripción',
    it: 'Cerca storie per titolo o descrizione',
  },
  'storyLibrary.searchResults': {
    en: 'Results',
    fr: 'Résultats',
    es: 'Resultados',
    it: 'Risultati',
  },
  'storyLibrary.searchEmpty': {
    en: 'No chronicles match your search.',
    fr: 'Aucune chronique ne correspond à votre recherche.',
    es: 'Ninguna crónica coincide con tu búsqueda.',
    it: 'Nessuna cronaca corrisponde alla ricerca.',
  },
  'storyLibrary.filterEmpty': {
    en: 'Nothing in this category yet.',
    fr: 'Rien dans cette catégorie pour le moment.',
    es: 'Nada en esta categoría por ahora.',
    it: 'Niente in questa categoria al momento.',
  },
  'storyLibrary.heroEmpty.title': {
    en: 'No chronicles match these filters',
    fr: 'Aucune chronique ne correspond à ces filtres',
    es: 'Ninguna crónica coincide con estos filtros',
    it: 'Nessuna cronaca corrisponde a questi filtri',
  },
  'storyLibrary.heroEmpty.hint': {
    en: 'Try another category, era, or search — or return to All to browse the full library.',
    fr: 'Essayez une autre catégorie, une autre ère ou une autre recherche — ou revenez à Tout pour parcourir toute la bibliothèque.',
    es: 'Prueba otra categoría, época o búsqueda, o vuelve a Todo para ver toda la biblioteca.',
    it: 'Prova un’altra categoria, epoca o ricerca — oppure torna a Tutto per sfogliare tutta la libreria.',
  },
  'storyLibrary.clearSearch': {
    en: 'Clear search',
    fr: 'Effacer la recherche',
    es: 'Borrar búsqueda',
    it: 'Cancella ricerca',
  },
  'storyLibrary.copyPlaybackLink': {
    en: 'Copy play link',
    fr: 'Copier le lien de lecture',
    es: 'Copiar enlace de reproducción',
    it: 'Copia link di riproduzione',
  },
  'storyLibrary.copyLibraryLink': {
    en: 'Copy library link',
    fr: 'Copier le lien vers la bibliothèque',
    es: 'Copiar enlace de la biblioteca',
    it: 'Copia link alla libreria',
  },
  'storyLibrary.section.related': {
    en: 'More in this collection',
    fr: 'Plus dans cette collection',
    es: 'Más en esta colección',
    it: 'Altro in questa collezione',
  },
  'journal.openInLibrary': {
    en: 'Open in story library',
    fr: 'Ouvrir dans la bibliothèque d’histoires',
    es: 'Abrir en la biblioteca de historias',
    it: 'Apri nella libreria di storie',
  },

  // --- Creator about modal & chrome ---
  'credits.headerButton': {
    en: 'Creator',
    fr: 'Créateur',
    es: 'Creador',
    it: 'Creatore',
  },
  'credits.headerButtonFull': {
    en: 'About the Creator',
    fr: 'À propos du créateur',
    es: 'Sobre el creador',
    it: 'Il creatore',
  },
  'credits.tooltip.label': {
    en: 'About the Creator',
    fr: 'À propos du créateur',
    es: 'Sobre el creador',
    it: 'Il creatore',
  },
  'credits.tooltip.hint': {
    en: 'The person behind this atlas, the vision, and how to work together.',
    fr: 'La personne derrière cet atlas, la vision et comment collaborer.',
    es: 'La persona detrás de este atlas, la visión y cómo colaborar.',
    it: 'La persona dietro questo atlante, la visione e come collaborare.',
  },
  'credits.aria.open': {
    en: 'Open about the creator',
    fr: 'Ouvrir à propos du créateur',
    es: 'Abrir sobre el creador',
    it: 'Apri informazioni sul creatore',
  },
  'credits.aria.close': {
    en: 'Close',
    fr: 'Fermer',
    es: 'Cerrar',
    it: 'Chiudi',
  },
  'credits.eyebrow': {
    en: 'Norman Atlas',
    fr: 'Norman Atlas',
    es: 'Norman Atlas',
    it: 'Norman Atlas',
  },
  'credits.title': {
    en: 'Guillaume Remi Couture',
    fr: 'Guillaume Remi Couture',
    es: 'Guillaume Remi Couture',
    it: 'Guillaume Remi Couture',
  },
  'credits.role': {
    en: 'UX/UI and interactive systems designer: game UI, digital products, and spatial storytelling.',
    fr: 'Designer UX/UI et systèmes interactifs : interfaces de jeu, produits numériques et narration spatiale.',
    es: 'Diseñador UX/UI y de sistemas interactivos: UI de juegos, productos digitales y narrativa espacial.',
    it: 'Designer UX/UI e sistemi interattivi: UI di gioco, prodotti digitali e narrazione spaziale.',
  },
  'credits.statusPill': {
    en: 'Available for select consulting & collaboration',
    fr: 'Disponible pour conseil et collaboration sélectifs',
    es: 'Disponible para consultoría y colaboración selectas',
    it: 'Disponibile per consulenza e collaborazione selezionate',
  },
  'credits.thesis': {
    en: 'This atlas is also a working example of how I design layered, narrative-driven systems.',
    fr: 'Cet atlas est aussi un exemple concret de ma façon de concevoir des systèmes narratifs et multicouches.',
    es: 'Este atlas es también un ejemplo práctico de cómo diseño sistemas narrativos y multicapa.',
    it: 'Questo atlante è anche un esempio concreto di come progetto sistemi narrativi e stratificati.',
  },
  'credits.aboutTitle': {
    en: 'About the Creator',
    fr: 'À propos du créateur',
    es: 'Sobre el creador',
    it: 'Il creatore',
  },
  'credits.about1': {
    en: 'For nearly twenty years I have designed UX/UI, interactive systems, and game interfaces for products used at scale, including collaborations with companies such as Disney, where clarity, guidance, and craft define every decision.',
    fr: 'Depuis près de vingt ans, je conçois des interfaces UX/UI, des systèmes interactifs et des interfaces de jeu pour des produits à grande échelle, notamment en collaboration avec des entreprises comme Disney, où clarté, accompagnement et rigueur guident chaque décision.',
    es: 'Durante casi veinte años he diseñado UX/UI, sistemas interactivos e interfaces de juego para productos a escala, incluyendo colaboraciones con empresas como Disney, donde claridad, orientación y oficio definen cada decisión.',
    it: 'Per quasi vent\'anni ho progettato UX/UI, sistemi interattivi e interfacce di gioco per prodotti su larga scala, incluse collaborazioni con aziende come Disney, dove chiarezza, orientamento e cura definiscono ogni scelta.',
  },
  'credits.about2': {
    en: 'Norman Atlas is personal research made tangible: history explored as a system you can move through, not a static page.',
    fr: 'Norman Atlas est une recherche personnelle rendue tangible : l\'histoire explorée comme un système que l\'on parcourt, pas une page statique.',
    es: 'Norman Atlas es investigación personal hecha tangible: historia explorada como un sistema por el que navegar, no una página estática.',
    it: 'Norman Atlas è ricerca personale resa tangibile: storia esplorata come un sistema da percorrere, non una pagina statica.',
  },
  'credits.whyTitle': {
    en: 'Why This Atlas Exists',
    fr: 'Pourquoi cet atlas existe',
    es: 'Por qué existe este atlas',
    it: 'Perché esiste questo atlante',
  },
  'credits.why1': {
    en: 'The story of the Normans goes far beyond textbooks: the migrations, the cultural transformations, the way Viking settlers became one of the most influential forces in medieval Europe. Most of that narrative is fragmented across sources and centuries.',
    fr: 'L\'histoire des Normands dépasse largement les manuels : les migrations, les transformations culturelles, la manière dont les colons vikings sont devenus l\'une des forces les plus influentes de l\'Europe médiévale. L\'essentiel de ce récit est dispersé entre les sources et les siècles.',
    es: 'La historia de los normandos va mucho más allá de los libros de texto: las migraciones, las transformaciones culturales, cómo los colonos vikingos se convirtieron en una de las fuerzas más influyentes de la Europa medieval. Gran parte de esa narrativa está fragmentada entre fuentes y siglos.',
    it: 'La storia dei Normanni va ben oltre i manuali: le migrazioni, le trasformazioni culturali, come i coloni vichinghi divennero una delle forze più influenti dell\'Europa medievale. Gran parte di questa narrazione è frammentata tra fonti e secoli.',
  },
  'credits.why2': {
    en: 'Normandy is a turning point, where identities shifted, cultures blended, and something new emerged. That ripple spread across England, Southern Italy, the Crusader states, and eventually into New France.',
    fr: 'La Normandie est un tournant, là où les identités se sont transformées, les cultures mêlées, et où quelque chose de nouveau est né. Cette onde s\'est propagée en Angleterre, dans le sud de l\'Italie, dans les États croisés, puis jusqu\'en Nouvelle-France.',
    es: 'Normandía es un punto de inflexión, donde cambiaron las identidades, se mezclaron las culturas y surgió algo nuevo. Esa onda se extendió por Inglaterra, el sur de Italia, los estados cruzados y, al final, a Nueva Francia.',
    it: 'La Normandia è una svolta, dove le identità si sono trasformate, le culture fuse, e qualcosa di nuovo è emerso. Quell\'onda si è diffusa in Inghilterra, nel sud Italia, negli stati crociati e infine nella Nuova Francia.',
  },
  'credits.why3': {
    en: 'I built this atlas to see that story clearly, as a connected system rather than scattered fragments.',
    fr: 'J\'ai construit cet atlas pour voir ce récit clairement, comme un système connecté plutôt que des fragments épars.',
    es: 'Construí este atlas para ver esa historia con claridad, como un sistema conectado y no como fragmentos dispersos.',
    it: 'Ho costruito questo atlante per vedere quella storia con chiarezza, come un sistema connesso anziché frammenti sparsi.',
  },
  'credits.showsTitle': {
    en: 'What This Project Shows',
    fr: 'Ce que montre ce projet',
    es: 'Lo que muestra este proyecto',
    it: 'Cosa mostra questo progetto',
  },
  'credits.showsIntro': {
    en: 'More than a map. A living atlas that lets you:',
    fr: 'Plus qu\'une carte. Un atlas vivant qui vous permet de :',
    es: 'Más que un mapa. Un atlas vivo que le permite:',
    it: 'Più di una mappa. Un atlante vivente che ti permette di:',
  },
  'credits.showsL1': {
    en: 'Follow migrations across time',
    fr: 'Suivre les migrations dans le temps',
    es: 'Seguir migraciones a lo largo del tiempo',
    it: 'Seguire le migrazioni nel tempo',
  },
  'credits.showsL2': {
    en: 'Explore where people came from and where they settled',
    fr: 'Explorer d\'où venaient les peuples et où ils se sont installés',
    es: 'Explorar de dónde venían las gentes y dónde se asentaron',
    it: 'Esplorare da dove venivano le genti e dove si stabilirono',
  },
  'credits.showsL3': {
    en: 'Understand how cultures evolved over centuries',
    fr: 'Comprendre comment les cultures ont évolué au fil des siècles',
    es: 'Entender cómo evolucionaron las culturas a lo largo de los siglos',
    it: 'Capire come le culture si sono evolute nel corso dei secoli',
  },
  'credits.showsL4': {
    en: 'Connect events across time in a visual, spatial way',
    fr: 'Relier des événements à travers le temps de façon visuelle et spatiale',
    es: 'Conectar acontecimientos a través del tiempo de forma visual y espacial',
    it: 'Collegare eventi nel tempo in modo visivo e spaziale',
  },
  'credits.showsOutro': {
    en: 'The same discipline I apply to complex products (structure, pacing, legibility) is what holds this experience together.',
    fr: 'La même rigueur que j\'applique aux produits complexes (structure, rythme, lisibilité) est ce qui donne sa cohérence à cette expérience.',
    es: 'La misma disciplina que aplico a productos complejos (estructura, ritmo, legibilidad) es lo que da cohesión a esta experiencia.',
    it: 'La stessa disciplina che applico ai prodotti complessi (struttura, ritmo, leggibilità) è ciò che tiene insieme questa esperienza.',
  },
  'credits.workTitle': {
    en: 'Work With Me',
    fr: 'Travaillons ensemble',
    es: 'Trabajemos juntos',
    it: 'Lavoriamo insieme',
  },
  'credits.workIntro': {
    en: 'If you want this level of systems thinking applied to a product, interface, or creative challenge, LinkedIn is the best way to start a conversation.',
    fr: 'Si vous souhaitez appliquer ce niveau de pensée systémique à un produit, une interface ou un défi créatif, LinkedIn est le meilleur moyen d\'entamer la conversation.',
    es: 'Si desea aplicar este nivel de pensamiento sistémico a un producto, interfaz o desafío creativo, LinkedIn es la mejor forma de iniciar una conversación.',
    it: 'Se vuoi applicare questo livello di pensiero sistemico a un prodotto, un\'interfaccia o una sfida creativa, LinkedIn è il modo migliore per iniziare una conversazione.',
  },
  'credits.workCta': {
    en: 'Connect on LinkedIn',
    fr: 'Me contacter sur LinkedIn',
    es: 'Conectar en LinkedIn',
    it: 'Contattami su LinkedIn',
  },
  'credits.workAvailable': {
    en: 'Available for:',
    fr: 'Disponible pour :',
    es: 'Disponible para:',
    it: 'Disponibile per:',
  },
  'credits.workL1': {
    en: 'UX/UI design consulting',
    fr: 'Conseil en design UX/UI',
    es: 'Consultoría de diseño UX/UI',
    it: 'Consulenza UX/UI',
  },
  'credits.workL2': {
    en: 'Interactive systems & product design',
    fr: 'Systèmes interactifs et design produit',
    es: 'Sistemas interactivos y diseño de producto',
    it: 'Sistemi interattivi e design di prodotto',
  },
  'credits.workL3': {
    en: 'Game UI/UX',
    fr: 'UI/UX de jeux',
    es: 'UI/UX de videojuegos',
    it: 'UI/UX per giochi',
  },
  'credits.workL4': {
    en: 'AI-assisted workflows & prototyping',
    fr: 'Flux assistés par l\'IA et prototypage',
    es: 'Flujos con IA y prototipado',
    it: 'Flussi assistiti dall\'IA e prototipazione',
  },
  'credits.supportTitle': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostenere l\'Atlante',
  },
  'credits.supportIntro': {
    en: 'Norman Atlas is an independent, long-term project. Your support funds continued research, new features, and historical expansion.',
    fr: 'Norman Atlas est un projet indépendant et de long terme. Votre soutien finance la recherche, les nouvelles fonctionnalités et l\'expansion historique.',
    es: 'Norman Atlas es un proyecto independiente a largo plazo. Su apoyo financia la investigación, nuevas funciones y la expansión histórica.',
    it: 'Norman Atlas è un progetto indipendente a lungo termine. Il tuo sostegno finanzia la ricerca, nuove funzionalità e l\'espansione storica.',
  },
  'credits.supportCta': {
    en: 'View support options',
    fr: 'Voir les options de soutien',
    es: 'Ver opciones de apoyo',
    it: 'Vedi le opzioni di sostegno',
  },
  'credits.ongoingTitle': {
    en: 'Ongoing Project',
    fr: 'Projet en cours',
    es: 'Proyecto en curso',
    it: 'Progetto in evoluzione',
  },
  'credits.ongoing1': {
    en: 'This atlas is continuously evolving, with new eras, deeper accuracy, and richer data layers over time. If you are exploring now, you are early; that is part of the journey.',
    fr: 'Cet atlas évolue en continu, avec de nouvelles époques, une précision accrue et des couches de données plus riches au fil du temps. Si vous explorez maintenant, vous êtes en avance ; cela fait partie du parcours.',
    es: 'Este atlas evoluciona continuamente, con nuevas épocas, mayor precisión y capas de datos más ricas con el tiempo. Si lo explora ahora, llega pronto; eso forma parte del camino.',
    it: 'Questo atlante evolve continuamente, con nuove epoche, maggiore accuratezza e strati di dati più ricchi nel tempo. Se lo esplori ora, sei in anticipo; fa parte del percorso.',
  },
  // --- Support modal ---
  'support.tooltip.label': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostenere l\'Atlante',
  },
  'support.tooltip.hint': {
    en: 'Help fund future atlas development',
    fr: 'Aidez à financer le développement futur de l\'atlas',
    es: 'Ayude a financiar el desarrollo futuro del atlas',
    it: 'Aiuta a finanziare lo sviluppo futuro dell\'atlante',
  },
  'support.aria.open': {
    en: 'Open support options',
    fr: 'Ouvrir les options de soutien',
    es: 'Abrir opciones de apoyo',
    it: 'Apri le opzioni di sostegno',
  },
  'support.aria.close': {
    en: 'Close support dialog',
    fr: 'Fermer la fenêtre de soutien',
    es: 'Cerrar el diálogo de apoyo',
    it: 'Chiudi la finestra di sostegno',
  },
  'support.headerButton': {
    en: 'Support',
    fr: 'Soutenir',
    es: 'Apoyar',
    it: 'Sostieni',
  },
  'support.headerButtonFull': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostieni l\'Atlante',
  },
  'support.modal.sectionLabel': {
    en: 'Support',
    fr: 'Soutien',
    es: 'Apoyo',
    it: 'Sostegno',
  },
  'support.modal.title': {
    en: 'Support Norman Atlas',
    fr: 'Soutenir Norman Atlas',
    es: 'Apoyar Norman Atlas',
    it: 'Sostenere Norman Atlas',
  },
  'support.modal.body1': {
    en: 'Norman Atlas is an independent historical project built to bring the Norman story to life through maps, timelines, and cinematic exploration.',
    fr: 'Norman Atlas est un projet historique indépendant conçu pour donner vie à l\'histoire normande à travers des cartes, des chronologies et une exploration cinématique.',
    es: 'Norman Atlas es un proyecto histórico independiente creado para dar vida a la historia normanda a través de mapas, cronologías y exploración cinematográfica.',
    it: 'Norman Atlas è un progetto storico indipendente creato per dare vita alla storia normanna attraverso mappe, cronologie ed esplorazione cinematografica.',
  },
  'support.modal.body2': {
    en: 'Your support helps fund continued development, research, new features, and historical expansion.',
    fr: 'Votre soutien finance le développement continu, la recherche, les nouvelles fonctionnalités et l\'expansion historique.',
    es: 'Su apoyo financia el desarrollo continuo, la investigación, nuevas funciones y la expansión histórica.',
    it: 'Il tuo sostegno finanzia lo sviluppo continuo, la ricerca, nuove funzionalità e l\'espansione storica.',
  },
  'support.modal.body3': {
    en: 'If you enjoy the project and want to help it grow, you can support it below.',
    fr: 'Si vous appréciez le projet et souhaitez l\'aider à grandir, vous pouvez le soutenir ci-dessous.',
    es: 'Si disfruta del proyecto y quiere ayudarlo a crecer, puede apoyarlo a continuación.',
    it: 'Se apprezzi il progetto e vuoi aiutarlo a crescere, puoi sostenerlo qui sotto.',
  },
  'support.modal.cta': {
    en: 'Support the Project',
    fr: 'Soutenir le projet',
    es: 'Apoyar el proyecto',
    it: 'Sostieni il progetto',
  },
  'support.mobileDrawer.label': {
    en: 'Support the Atlas',
    fr: 'Soutenir l\'Atlas',
    es: 'Apoyar el Atlas',
    it: 'Sostenere l\'Atlante',
  },

  // --- Changelog / recent updates ---
  'changelog.tooltip.label': {
    en: 'Recent updates',
    fr: 'Mises à jour récentes',
    es: 'Actualizaciones recientes',
    it: 'Aggiornamenti recenti',
  },
  'changelog.tooltip.hint': {
    en: 'Shipped features, new stories, and atlas improvements.',
    fr: 'Fonctionnalités livrées, nouveaux récits et améliorations de l’atlas.',
    es: 'Funciones publicadas, nuevas historias y mejoras del atlas.',
    it: 'Funzionalità rilasciate, nuove storie e miglioramenti dell’atlante.',
  },
  'changelog.aria.open': {
    en: 'Open recent updates',
    fr: 'Ouvrir les mises à jour récentes',
    es: 'Abrir actualizaciones recientes',
    it: 'Apri aggiornamenti recenti',
  },
  'changelog.aria.close': {
    en: 'Close updates dialog',
    fr: 'Fermer les mises à jour',
    es: 'Cerrar actualizaciones',
    it: 'Chiudi la finestra degli aggiornamenti',
  },
  'shareView.tooltip.label': {
    en: 'Share this view',
    fr: 'Partager cette vue',
    es: 'Compartir esta vista',
    it: 'Condividi questa vista',
  },
  'shareView.tooltip.hint': {
    en: 'Copy a link that restores this exact map position, era, and layers.',
    fr: 'Copier un lien qui restaure cette position, cette époque et ces couches.',
    es: 'Copiar un enlace que restaura esta posición, era y capas.',
    it: 'Copia un link che ripristina posizione, era e livelli della mappa.',
  },
  'shareView.aria': {
    en: 'Copy shareable link to this view',
    fr: 'Copier le lien partageable vers cette vue',
    es: 'Copiar enlace para compartir esta vista',
    it: 'Copia il link condivisibile di questa vista',
  },
  'shareView.copied': {
    en: 'Link copied!',
    fr: 'Lien copié !',
    es: '¡Enlace copiado!',
    it: 'Link copiato!',
  },
  'shareView.shared': {
    en: 'Shared!',
    fr: 'Partagé !',
    es: '¡Compartido!',
    it: 'Condiviso!',
  },
  'shareView.failed': {
    en: 'Could not copy link',
    fr: 'Impossible de copier le lien',
    es: 'No se pudo copiar el enlace',
    it: 'Impossibile copiare il link',
  },
  'shareView.mobileDrawer.label': {
    en: 'Share this view',
    fr: 'Partager cette vue',
    es: 'Compartir esta vista',
    it: 'Condividi questa vista',
  },
  'changelog.modal.sectionLabel': {
    en: 'Recent updates',
    fr: 'Mises à jour récentes',
    es: 'Actualizaciones recientes',
    it: 'Aggiornamenti recenti',
  },
  'changelog.modal.title': {
    en: 'What’s new',
    fr: 'Quoi de neuf',
    es: 'Novedades',
    it: 'Novità',
  },
  'changelog.mobileDrawer.label': {
    en: 'Recent updates',
    fr: 'Mises à jour récentes',
    es: 'Actualizaciones recientes',
    it: 'Aggiornamenti recenti',
  },

  'coutureStory.surnameHeading': {
    en: 'The name Couture',
    fr: 'Le nom Couture',
    es: 'El apellido Couture',
    it: 'Il cognome Couture',
  },
  'coutureStory.fullStoryHeading': {
    en: 'His life in full',
    fr: 'Sa vie, en bref',
    es: 'Su vida, en detalle',
    it: 'La sua vita',
  },
  'coutureStory.followMap': {
    en: 'Follow his story on the map',
    fr: 'Suivre son parcours sur la carte',
    es: 'Seguir su historia en el mapa',
    it: 'Segui la sua storia sulla mappa',
  },
  'atlasJournal.tooltip.label': {
    en: 'Atlas Journal',
    fr: 'Journal de l\'Atlas',
    es: 'Diario del Atlas',
    it: 'Diario dell\'Atlante',
  },
  'atlasJournal.tooltip.hint': {
    en: 'Glossary, timeline, Norman names, and how to read the atlas.',
    fr: 'Glossaire, chronologie, patronymes normands et guide de l\'atlas.',
    es: 'Glosario, cronología, apellidos normandos y guía del atlas.',
    it: 'Glossario, cronologia, cognomi normanni e guida dell\'atlante.',
  },
  'atlasJournal.aria.open': {
    en: 'Open atlas journal',
    fr: 'Ouvrir le journal de l\'atlas',
    es: 'Abrir el diario del atlas',
    it: 'Apri il diario dell\'atlante',
  },

  'dock.more': {
    en: 'More journeys',
    fr: 'Plus de parcours',
    es: 'Más recorridos',
    it: 'Altri percorsi',
  },
  'dock.flythroughs': {
    en: 'Flythroughs',
    fr: 'Survols',
    es: 'Sobrevuelos',
    it: 'Sorvoli',
  },
  'dock.stories': {
    en: 'Story Arcs',
    fr: 'Arcs narratifs',
    es: 'Arcos narrativos',
    it: 'Archi narrativi',
  },

  'flythrough.label': {
    en: 'Cinematic Flythrough',
    fr: 'Survol cinématique',
    es: 'Sobrevuelo cinematográfico',
    it: 'Sorvolo cinematico',
  },
  'flythrough.exit': {
    en: 'Exit flythrough',
    fr: 'Quitter le survol',
    es: 'Salir del sobrevuelo',
    it: 'Esci dal sorvolo',
  },
  'flythrough.playing': {
    en: 'Flying along route...',
    fr: 'Survol de la route...',
    es: 'Sobrevolando la ruta...',
    it: 'In volo sulla rotta...',
  },

  // --- Atlas Ledger / Gamification ---
  'ledger.tooltip.label': {
    en: 'Atlas Ledger',
    fr: 'Registre de l\'atlas',
    es: 'Registro del atlas',
    it: 'Registro dell\'atlante',
  },
  'ledger.tooltip.hint': {
    en: 'Side panel on the map: coverage, full milestone list, expeditions, and share.',
    fr: 'Panneau latéral sur la carte : couverture, jalons détaillés, expéditions et partage.',
    es: 'Panel lateral en el mapa: cobertura, lista completa de hitos, expediciones y compartir.',
    it: 'Pannello laterale sulla mappa: copertura, elenco traguardi, spedizioni e condivisione.',
  },
  'ledger.aria.open': {
    en: 'Open atlas ledger side panel',
    fr: 'Ouvrir le panneau du registre de l\'atlas',
    es: 'Abrir el panel lateral del registro del atlas',
    it: 'Apri il pannello laterale del registro dell\'atlante',
  },
  'ledger.heading': {
    en: 'Your Atlas Ledger',
    fr: 'Votre registre',
    es: 'Tu registro',
    it: 'Il tuo registro',
  },
  'ledger.coverage': {
    en: 'Coverage',
    fr: 'Couverture',
    es: 'Cobertura',
    it: 'Copertura',
  },
  'ledger.milestones': {
    en: 'Milestones',
    fr: 'Jalons',
    es: 'Hitos',
    it: 'Traguardi',
  },
  'ledger.expeditions': {
    en: 'Expeditions',
    fr: 'Expéditions',
    es: 'Expediciones',
    it: 'Spedizioni',
  },
  'ledger.places': {
    en: 'Places',
    fr: 'Lieux',
    es: 'Lugares',
    it: 'Luoghi',
  },
  'ledger.regions': {
    en: 'Regions',
    fr: 'Régions',
    es: 'Regiones',
    it: 'Regioni',
  },
  'ledger.journeys': {
    en: 'Journeys',
    fr: 'Voyages',
    es: 'Viajes',
    it: 'Viaggi',
  },
  'ledger.segments': {
    en: 'Segments',
    fr: 'Segments',
    es: 'Segmentos',
    it: 'Segmenti',
  },
  'ledger.eras': {
    en: 'Eras explored',
    fr: 'Époques explorées',
    es: 'Épocas exploradas',
    it: 'Epoche esplorate',
  },
  'ledger.stories': {
    en: 'Stories completed',
    fr: 'Récits terminés',
    es: 'Relatos completados',
    it: 'Racconti completati',
  },
  'ledger.empty': {
    en: 'Begin exploring the atlas to fill your ledger.',
    fr: 'Explorez l\'atlas pour remplir votre registre.',
    es: 'Explora el atlas para llenar tu registro.',
    it: 'Esplora l\'atlante per compilare il tuo registro.',
  },
  'ledger.export': {
    en: 'Export progress',
    fr: 'Exporter la progression',
    es: 'Exportar progreso',
    it: 'Esporta progresso',
  },
  'ledger.import': {
    en: 'Import progress',
    fr: 'Importer la progression',
    es: 'Importar progreso',
    it: 'Importa progresso',
  },
  'ledger.reset': {
    en: 'Reset progress',
    fr: 'Réinitialiser',
    es: 'Reiniciar',
    it: 'Reimposta',
  },
  'ledger.reset.confirm': {
    en: 'This will erase all exploration data. Continue?',
    fr: 'Cela effacera toutes les données d\'exploration. Continuer ?',
    es: 'Esto borrará todos los datos de exploración. ¿Continuar?',
    it: 'Questo cancellerà tutti i dati di esplorazione. Continuare?',
  },
  'ledger.role.explorer': {
    en: 'Explorer',
    fr: 'Explorateur',
    es: 'Explorador',
    it: 'Esploratore',
  },
  'ledger.role.historian': {
    en: 'Historian',
    fr: 'Historien',
    es: 'Historiador',
    it: 'Storico',
  },
  'ledger.role.cartographer': {
    en: 'Cartographer',
    fr: 'Cartographe',
    es: 'Cartógrafo',
    it: 'Cartografo',
  },
  'ledger.role.chronicler': {
    en: 'Chronicler',
    fr: 'Chroniqueur',
    es: 'Cronista',
    it: 'Cronista',
  },
  'toast.discovered': {
    en: 'New entry recorded',
    fr: 'Nouvelle entrée enregistrée',
    es: 'Nueva entrada registrada',
    it: 'Nuova voce registrata',
  },
  'toast.milestone': {
    en: 'Milestone reached',
    fr: 'Jalon atteint',
    es: 'Hito alcanzado',
    it: 'Traguardo raggiunto',
  },
  'ledger.mobileDrawer.label': {
    en: 'Atlas ledger (quick view)',
    fr: 'Registre (vue rapide)',
    es: 'Registro (vista rápida)',
    it: 'Registro (vista rapida)',
  },
  'expedition.inProgress': {
    en: 'In progress',
    fr: 'En cours',
    es: 'En curso',
    it: 'In corso',
  },
  'expedition.completed': {
    en: 'Completed',
    fr: 'Terminée',
    es: 'Completada',
    it: 'Completata',
  },
  'expedition.start': {
    en: 'Begin expedition',
    fr: 'Commencer l\'expédition',
    es: 'Comenzar expedición',
    it: 'Inizia spedizione',
  },
  'milestone.modal.sealed': {
    en: 'Milestone sealed',
    fr: 'Jalon scellé',
    es: 'Hito sellado',
    it: 'Traguardo sigillato',
  },
  'milestone.modal.continue': {
    en: 'Continue',
    fr: 'Continuer',
    es: 'Continuar',
    it: 'Continua',
  },
  'milestone.modal.share': {
    en: 'Share',
    fr: 'Partager',
    es: 'Compartir',
    it: 'Condividi',
  },
  'milestone.modal.more': {
    en: 'more milestones',
    fr: 'autres jalons',
    es: 'más hitos',
    it: 'altri traguardi',
  },
  'milestone.share.text': {
    en: 'I just unlocked "{title}" on the Norman Atlas!',
    fr: 'Je viens de débloquer « {title} » sur le Norman Atlas !',
    es: '¡Acabo de desbloquear "{title}" en el Norman Atlas!',
    it: 'Ho appena sbloccato "{title}" sul Norman Atlas!',
  },
  'share.firstExploration.sealed': {
    en: 'First entry in your ledger',
    fr: 'Première entrée dans votre registre',
    es: 'Primera entrada en tu registro',
    it: 'Prima voce nel tuo registro',
  },
  'share.firstExploration.title': {
    en: 'You opened: {label}',
    fr: 'Vous avez ouvert : {label}',
    es: 'Has abierto: {label}',
    it: 'Hai aperto: {label}',
  },
  'share.firstExploration.subtitle': {
    en: 'Share the Norman Atlas with someone who loves maps and history.',
    fr: 'Partagez le Norman Atlas avec quelqu’un qui aime les cartes et l’histoire.',
    es: 'Comparte el Norman Atlas con alguien a quien le gusten los mapas y la historia.',
    it: 'Condividi il Norman Atlas con chi ama mappe e storia.',
  },
  'share.firstExploration.shareBody': {
    en: 'I just started exploring the Norman Atlas — first stop: {label}',
    fr: 'Je viens de commencer à explorer le Norman Atlas — premier arrêt : {label}',
    es: 'Acabo de empezar a explorar el Norman Atlas — primera parada: {label}',
    it: 'Ho appena iniziato a esplorare il Norman Atlas — prima tappa: {label}',
  },
  'share.firstStory.shareBody': {
    en: 'I finished my first story arc on the Norman Atlas: "{title}"',
    fr: 'J’ai terminé mon premier arc narratif sur le Norman Atlas : « {title} »',
    es: 'Terminé mi primer arco narrativo en el Norman Atlas: «{title}»',
    it: 'Ho completato il mio primo arco narrativo sul Norman Atlas: «{title}»',
  },
  'ledger.shareProgressHeading': {
    en: 'Share your progress',
    fr: 'Partager votre progression',
    es: 'Comparte tu progreso',
    it: 'Condividi i tuoi progressi',
  },
  'story.seal.recorded': {
    en: 'Arc recorded in your ledger',
    fr: 'Arc enregistré dans votre registre',
    es: 'Arco registrado en tu registro',
    it: 'Arco registrato nel tuo registro',
  },
  'expedition.chip.progress': {
    en: '{done}/{total}',
    fr: '{done}/{total}',
    es: '{done}/{total}',
    it: '{done}/{total}',
  },
  'story.seal.subtitle': {
    en: 'Your progress has been saved in the Atlas Ledger.',
    fr: 'Votre progression a été enregistrée dans le registre de l\'atlas.',
    es: 'Tu progreso se ha guardado en el registro del atlas.',
    it: 'I tuoi progressi sono stati salvati nel registro dell\'atlante.',
  },
  'ledger.affordance.mobile': {
    en: 'Open Ledger',
    fr: 'Ouvrir le registre',
    es: 'Abrir registro',
    it: 'Apri registro',
  },

  'profile.tooltip.label': {
    en: 'Traveller Profile',
    fr: 'Profil du voyageur',
    es: 'Perfil del viajero',
    it: 'Profilo del viaggiatore',
  },
  'profile.tooltip.hint': {
    en: 'Full page: rank, streak, weekly challenge, coverage overview, and achievements grid.',
    fr: 'Page complète : rang, série, défi hebdomadaire, couverture et grille de succès.',
    es: 'Página completa: rango, racha, reto semanal, cobertura y cuadrícula de logros.',
    it: 'Pagina intera: rango, serie, sfida settimanale, copertura e griglia traguardi.',
  },
  'profile.aria.open': {
    en: 'Open traveller profile page',
    fr: 'Ouvrir la page profil du voyageur',
    es: 'Abrir la página de perfil del viajero',
    it: 'Apri la pagina profilo del viaggiatore',
  },
  'profile.mobileDrawer.label': {
    en: 'Traveller profile (full page)',
    fr: 'Profil du voyageur (page)',
    es: 'Perfil del viajero (página)',
    it: 'Profilo del viaggiatore (pagina)',
  },
  'profile.pageHeader': {
    en: 'Traveller profile',
    fr: 'Profil du voyageur',
    es: 'Perfil del viajero',
    it: 'Profilo del viaggiatore',
  },
  'profile.journeyTitle': {
    en: 'Your journey',
    fr: 'Votre parcours',
    es: 'Tu recorrido',
    it: 'Il tuo percorso',
  },
  'profile.dataSection': {
    en: 'Data',
    fr: 'Données',
    es: 'Datos',
    it: 'Dati',
  },
  'profile.achievements.summary': {
    en: 'Achievements',
    fr: 'Succès',
    es: 'Logros',
    it: 'Obiettivi',
  },
  'profile.achievements.unlockedCount': {
    en: '{unlocked} of {total} unlocked',
    fr: '{unlocked} sur {total} débloqués',
    es: '{unlocked} de {total} desbloqueados',
    it: '{unlocked} di {total} sbloccati',
  },
  'profile.achievement.tier': {
    en: 'Tier {tier}',
    fr: 'Niveau {tier}',
    es: 'Nivel {tier}',
    it: 'Grado {tier}',
  },

  // --- Detail FAB (mobile reopen) ---
  'detail.fab.hint': {
    en: 'Tap to explore this story',
    fr: 'Touchez pour explorer ce récit',
    es: 'Toca para explorar esta historia',
    it: 'Tocca per esplorare questa storia',
  },
  'detail.fab.hintDismiss': {
    en: 'Got it',
    fr: 'Compris',
    es: 'Entendido',
    it: 'Capito',
  },
  'detail.fab.hintStoryEra': {
    en: 'Era details & context',
    fr: 'Détails et contexte de l\'époque',
    es: 'Detalles y contexto de la era',
    it: 'Dettagli e contesto dell\'era',
  },
  'detail.fab.aria': {
    en: 'Open place story and details',
    fr: 'Ouvrir le récit et les détails du lieu',
    es: 'Abrir la historia y los detalles del lugar',
    it: 'Apri la storia e i dettagli del luogo',
  },
  'detail.fab.tooltipLabel': {
    en: 'Information panel',
    fr: 'Panneau d’information',
    es: 'Panel de información',
    it: 'Pannello informativo',
  },
  'detail.fab.tooltipHint': {
    en: 'Expand for context and details about your current map selection.',
    fr: 'Agrandir pour le contexte et les détails de la sélection sur la carte.',
    es: 'Amplía para ver contexto y detalles de tu selección en el mapa.',
    it: 'Espandi per contesto e dettagli sulla selezione sulla mappa.',
  },
  // --- Story Launcher ---
  'launcher.open': {
    en: 'Explore Stories',
    fr: 'Explorer les récits',
    es: 'Explorar historias',
    it: 'Esplora i racconti',
  },
  'launcher.title': {
    en: 'Stories',
    fr: 'Récits',
    es: 'Historias',
    it: 'Racconti',
  },
  'launcher.headline.kicker': {
    en: 'Stories',
    fr: 'Récits',
    es: 'Historias',
    it: 'Racconti',
  },
  'launcher.tagline': {
    en: 'Picks for the era shown on your map. Open the library to browse every arc and journey.',
    fr: 'Sélection pour l\u2019\u00e9poque affich\u00e9e sur votre carte. Ouvrez la biblioth\u00e8que pour parcourir tous les arcs et parcours.',
    es: 'Selección para la época que ves en el mapa. Abre la biblioteca para ver todos los arcos y recorridos.',
    it: 'Scelti per l\u2019epoca mostrata sulla mappa. Apri la biblioteca per tutti gli archi e i percorsi.',
  },
  'launcher.moreFromLibrary': {
    en: 'More from the library',
    fr: 'Plus depuis la biblioth\u00e8que',
    es: 'Más de la biblioteca',
    it: 'Altro dalla biblioteca',
  },
  'launcher.section.thisEra': {
    en: 'In this era',
    fr: 'Dans cette \u00e9poque',
    es: 'En esta época',
    it: 'In quest\u2019epoca',
  },
  'launcher.section.recommended': {
    en: 'Recommended for you',
    fr: 'Recommandé pour vous',
    es: 'Recomendado para ti',
    it: 'Consigliato per te',
  },
  'launcher.section.otherPeriodsArcs': {
    en: 'Other periods & arcs',
    fr: 'Autres p\u00e9riodes et arcs',
    es: 'Otras \u00e9pocas y arcos',
    it: 'Altri periodi e archi',
  },
  'launcher.section.journeys': {
    en: 'Full Journeys',
    fr: 'Parcours complets',
    es: 'Recorridos completos',
    it: 'Percorsi completi',
  },
  'launcher.section.flythroughs': {
    en: 'Cinematic Flights',
    fr: 'Survols cinématiques',
    es: 'Sobrevuelos cinematográficos',
    it: 'Sorvoli cinematici',
  },
  'launcher.contextual.continue': {
    en: 'Continue',
    fr: 'Continuer',
    es: 'Continuar',
    it: 'Continua',
  },
  'launcher.badge.continue': {
    en: 'Continue',
    fr: 'Reprendre',
    es: 'Continuar',
    it: 'Riprendi',
  },
  'launcher.badge.completed': {
    en: 'Completed',
    fr: 'Terminé',
    es: 'Completado',
    it: 'Completato',
  },
  'launcher.journey.full': {
    en: 'Full Atlas Chronicle',
    fr: 'Chronique complète de l\'atlas',
    es: 'Crónica completa del atlas',
    it: 'Cronaca completa dell\'atlante',
  },
  'launcher.browseAll': {
    en: 'Open full story library',
    fr: 'Ouvrir la biblioth\u00e8que compl\u00e8te',
    es: 'Abrir la biblioteca completa',
    it: 'Apri la biblioteca completa',
  },
  'launcher.browseAll.hint': {
    en: 'Every arc, journey, and filter',
    fr: 'Tous les arcs, parcours et filtres',
    es: 'Todos los arcos, recorridos y filtros',
    it: 'Tutti gli archi, percorsi e filtri',
  },
  'launcher.aria.close': {
    en: 'Close story launcher',
    fr: 'Fermer le lanceur de récits',
    es: 'Cerrar lanzador de historias',
    it: 'Chiudi lanciatore di racconti',
  },
  'launcher.duration': {
    en: '~{min} min',
    fr: '~{min} min',
    es: '~{min} min',
    it: '~{min} min',
  },

  // --- Gamification: Rank & Streak -----------------------------------------
  'rank.novice': {
    en: 'Novice',
    fr: 'Novice',
  },
  'rank.apprentice': {
    en: 'Apprentice',
    fr: 'Apprenti',
  },
  'rank.journeyman': {
    en: 'Journeyman',
    fr: 'Compagnon',
  },
  'rank.adept': {
    en: 'Adept',
    fr: 'Adepte',
  },
  'rank.scholar': {
    en: 'Scholar',
    fr: 'Érudit',
  },
  'rank.master': {
    en: 'Master',
    fr: 'Maître',
  },
  'rank.grandMaster': {
    en: 'Grand Master',
    fr: 'Grand Maître',
  },
  'rank.label': {
    en: 'Atlas Rank',
    fr: 'Rang de l\'Atlas',
  },
  'streak.label': {
    en: 'Streak',
    fr: 'Série',
  },
  'streak.days': {
    en: '{n} day streak',
    fr: 'Série de {n} jours',
  },
  'streak.best': {
    en: 'Best: {n}',
    fr: 'Record : {n}',
  },

  // --- Gamification: Challenges --------------------------------------------
  'challenge.heading': {
    en: 'Weekly Challenge',
    fr: 'Défi de la semaine',
  },
  'challenge.completed': {
    en: 'Completed',
    fr: 'Terminé',
  },
  'challenge.progress': {
    en: '{done}/{total}',
    fr: '{done}/{total}',
  },
  'challenge.noCurrent': {
    en: 'No challenge this week',
    fr: 'Aucun défi cette semaine',
  },

  // --- Gamification: Coverage bars -----------------------------------------
  'coverage.percent': {
    en: '{pct}%',
    fr: '{pct} %',
  },
  'coverage.label': {
    en: 'Completion',
    fr: 'Progression',
  },

  // --- Gamification: Hidden milestones -------------------------------------
  'milestone.hidden.title': {
    en: '???',
    fr: '???',
  },
  'milestone.hidden.description': {
    en: 'Continue exploring to reveal this milestone.',
    fr: 'Continuez à explorer pour révéler ce jalon.',
  },

  // --- Retention strip ------------------------------------------------------
  'retention.continue': {
    en: 'Continue',
    fr: 'Reprendre',
    es: 'Continuar',
    it: 'Continua',
  },
  'retention.streakDays': {
    en: '{n}-day streak',
    fr: 'Série de {n} j',
    es: 'Racha de {n} días',
    it: 'Serie di {n} giorni',
  },
  'retention.challengeProgress': {
    en: 'Challenge {done}/{total}',
    fr: 'Défi {done}/{total}',
    es: 'Desafío {done}/{total}',
    it: 'Sfida {done}/{total}',
  },

  // --- Journal resume section -----------------------------------------------
  'journal.resume.heading': {
    en: 'Pick Up Where You Left Off',
    fr: 'Reprenez là où vous en étiez',
    es: 'Retoma donde lo dejaste',
    it: 'Riprendi da dove eri rimasto',
  },
  'journal.resume.step': {
    en: 'Step {n}',
    fr: 'Étape {n}',
    es: 'Paso {n}',
    it: 'Passo {n}',
  },
} as const satisfies StringTable;

export type UiStringKey = keyof typeof STRINGS;

/**
 * Look up a UI string by key and locale, falling back to English.
 */
export function t(key: UiStringKey, locale: AtlasLocale): string {
  const entry = STRINGS[key];
  return (entry as Record<string, string | undefined>)[locale] ?? entry.en;
}
