// Auto-generated by scripts/build-gfna-datasets.mjs — do not edit by hand.
// Source: data/atlas/gfna-dna-records.jsonl (presumed Y-DNA rows only)
// Re-run:  npm run build:gfna

import type { NfYdnaFeature, NfYdnaCollection } from './new-france-ydna-types';

export const nfYdnaPresumedGeoJson: NfYdnaCollection = {
  "type": "FeatureCollection",
  "features": []
} as NfYdnaCollection;

export function getNfYdnaPresumedFeature(id: string): NfYdnaFeature | undefined {
  return nfYdnaPresumedGeoJson.features.find((f) => f.properties.id === id);
}
