// Auto-generated by scripts/build-gfna-datasets.mjs — do not edit by hand.
// Source: data/atlas/gfna-dna-records.jsonl (mtDNA rows)
// Re-run:  npm run build:gfna

import type { NfMtDnaFeature, NfMtDnaCollection } from './gfna-mtdna-types';

export const nfMtdnaGeoJson: NfMtDnaCollection = {
  "type": "FeatureCollection",
  "features": []
} as NfMtDnaCollection;

export function getNfMtdnaFeature(id: string): NfMtDnaFeature | undefined {
  return nfMtdnaGeoJson.features.find((f) => f.properties.id === id);
}
